<%@ Page Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Blog.aspx.cs" Inherits="WebApplication1.Blog" Title="Blog" %>
<%@ OutputCache Duration="21600" VaryByParam="None" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>

        $(document).ready(function () {
            blogPage();
            generalLook();
            menu();
        });
    </script>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle">Blog</div>
    </div>
    <!-- header end -->
    <div class="nBlogMainContainer">
        <asp:Repeater ID="RepeaterBlog" runat="server">
            <ItemTemplate>
                <div class="nBlogBlogEach">
                    <div class="nBlogTitle">
                        <asp:HyperLink ID="HyperLinkTitle" runat="server" NavigateUrl='<%# "~/Blog/"+ Eval("EntryId") %>'
                            Text='<%# Eval("Title") %>'></asp:HyperLink>
                    </div>
                    <div class="nBlogTime">
                        <div class="nSmallIcon nBlogClock"></div>
                        <asp:Label ID="LabelDate" runat="server" Text='<%# Eval("SubmitDate") %>'></asp:Label>
                    </div>
                    <div class="clear"></div>
                    <div class="nBlogBody">
                        <asp:Literal ID="LiteralBody" runat="server" Text='<%# Eval("Body") %>'></asp:Literal>
                    </div>
                    <hr />
                    <!-- <asp:HyperLink ID="HyperLinkPermalink" runat="server" NavigateUrl='<%# "~/Blog/"+ Eval("EntryId") + "/" + Eval("BrowserTitle") %>'>Permalink</asp:HyperLink> -->
                </div>
            </ItemTemplate>
        </asp:Repeater>
        <div class="hidden">
            <asp:Label ID="Label1" runat="server" CssClass="LabelNormal" Font-Bold="True"
                Text="Blog"></asp:Label>
        </div>
    </div>

</asp:Content>


