<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/MasterPageUser.Master" CodeBehind="BlogEntries.aspx.cs" Inherits="WebApplication1.BlogEntries" %>
<%@ OutputCache Duration="21600" VaryByParam="id" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Blog</title>
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>
    
    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script> 
    <script>
        $(document).ready(function () {
            blog();
            generalLook();
            menu();
        });
    </script>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle">Blog</div>
    </div>
    <!-- header end -->
    <div class="nBlogMainContainer">

        <div class="nBlogTitle">
            <asp:Label ID="LabelTitle" runat="server"></asp:Label>
        </div>
        <div class="nBlogTime">
            <div class="nBlogClock"></div>
            <asp:Label ID="LabelDate" runat="server"></asp:Label>
        </div>
        <div class="clear"></div>
        <div class="nBlogBody">
            <asp:Literal ID="LiteralBody" runat="server"></asp:Literal>
        </div>
        <br />
        <a class="nEVShareButtonFB" target="_blank" href="#">
            <img class="nEVshareImg" src="../../Images/Icons/fb.png" alt="facebook" width="32" height="32" /></a>
        <a class="nEVShareButtonTwitter" target="_blank" href="#">
            <img class="nEVshareImg" src="../../Images/Icons/twitter.png" alt="Twitter" width="32" height="32" /></a>
        <hr />
        <div class="hidden">
        </div>
    </div>
    <!--
    
        <div>
            <asp:Label ID="Label1" runat="server" Text="Blog"></asp:Label>
            <asp:Image ID="Image4" runat="server" Height="22px"
                ImageUrl="~/Images/Icons/right22.png" Width="22px" />
            <asp:HyperLink ID="HyperLink19" runat="server" NavigateUrl="~/Blog">Back to blog&#39;s home</asp:HyperLink>
            <br />
            
            <br />
            <asp:Label ID="LabelCat0" runat="server" Text="Submit Date:"></asp:Label>
            
            <br />
            
            <asp:Panel ID="PanelNext" runat="server" Visible="False">
                <asp:Image ID="Image12" runat="server" Height="22px"
                    ImageUrl="~/images/icons/right22.png" Width="22px" />
                <asp:HyperLink ID="HyperLinkNext" runat="server">[HyperLinkPervious]</asp:HyperLink>
            </asp:Panel>
            <asp:Panel ID="PanelPervious" runat="server" Visible="False">
                <asp:HyperLink ID="HyperLinkPervious" runat="server">[HyperLinkPervious]</asp:HyperLink>
                <asp:Image ID="Image11" runat="server" Height="22px"
                    ImageUrl="~/images/icons/left22.png" Width="22px" />
            </asp:Panel>
        </div>
    </form>
    -->
    <div class="nExploreFooter nThickFooter ">
        <div class="nFooterButton nProfileMessageButton">
            <div class="nFooter1Image nProfileImageGrey"></div>
            BACK TO BLOG</div>
    </div>
</asp:Content>


