<%@ Page Title="Completion" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Completion.aspx.cs" Inherits="WebApplication1.Completion" EnableEventValidation="false" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>
    
    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script> 
    <script>
        $(document).ready(function () {
            completionPage();
            generalLook();
            menu();
        });
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nCompletionTransparentBG">
        <br />
        <div class="nCompletionHeader">
            You are only seconds away of completing your profile :)
        </div>
        <div class="nEventCoverBox nEventCoverBoxSides hidden">
            <!-- <div class="nCompletionCircle nRight">
            <div class="nCompletionPhotoText nCompletionPhotoTextSideLeft">Choose another one</div> 
        </div>-->

        </div>
        <div class="nEventCoverBox">
            <div class="nCompletionCircleMain nCompletionCircle">
                <div class="nCompletionPhotoIcon nCompletionPhotoInside"></div>
                <div class="nCompletionPhotoText nCompletionPhotoInside">Add Photo</div>
            </div>
        </div>

        <div class="clear"></div>
        <br />
        <div class="nCompletionBox">
            <div class="nCompletionBoxFirst nCompletionBoxFirstFN invisible">
                <div class="nCompletionIcon nCompletionIconFN"></div>
                <div class="nCompletionName">First Name</div>
                <div class="nCompletionStatus"></div>
            </div>
            <div class="nCompletionBoxSecond ">
                <div class="nCompletionIcon nCompletionIconFN"></div>
                <div class="nCompletionName">First Name</div>
                <div class="nCompletionArrowFN nSIRowEnterArrow nCompletionArrow nValidatorButton invisible"></div>
                <div class="nCompletionStatus"></div>
                <div class="nCompletionInput">
                    <asp:TextBox ID="TextBoxFirstName" runat="server" CssClass="nCompletionTextInput nCompletionTextInputFN" data-role="none"></asp:TextBox>
                </div>
            </div>
        </div>
        <div class="nCompletionValidationErrorMessage invisible nCompletionFNError">Please enter a valid first name</div>
        <div class="nCompletionBox">
            <div class="nCompletionBoxFirst nCompletionBoxFirstLN invisible">
                <div class="nCompletionIcon nCompletionIconLN"></div>
                <div class="nCompletionName">Last Name</div>

            </div>
            <div class="nCompletionBoxSecond ">
                <div class="nCompletionIcon nCompletionIconFN"></div>
                <div class="nCompletionName">Last Name</div>
                <div class="nCompletionArrowLN nSIRowEnterArrow nCompletionArrow nValidatorButton invisible"></div>
                <div class="nCompletionStatus"></div>
                <div class="nCompletionInput">
                    <asp:TextBox ID="TextBoxLastName" runat="server" CssClass="nCompletionTextInput nCompletionTextInputLN" data-role="none"></asp:TextBox>
                </div>
            </div>
        </div>
        <div class="nCompletionValidationErrorMessage invisible nCompletionLNError">Please enter a valid last name</div>
        <div class="nCompletionBox">
            <div class="nCompletionBoxFirst nCompletionBoxFirstUN invisible">
                <div class="nCompletionIcon nCompletionIconUN"></div>
                <div class="nCompletionName">Username</div>

            </div>
            <div class="nCompletionBoxSecond ">
                <div class="nCompletionIcon nCompletionIconUN"></div>
                <div class="nCompletionName">Username</div>
                <div class="nCompletionArrowUN nSIRowEnterArrow nCompletionArrow nValidatorButton invisible "></div>
                <div class="nCompletionStatus"></div>
                <div class="nCompletionInput">
                    <asp:TextBox ID="TextBoxUsername" CssClass="nCompletionTextInput nCompletionTextInputUN" runat="server" data-role="none"></asp:TextBox>
                </div>
            </div>
        </div>
        <div class="nCompletionValidationErrorMessage invisible nCompletionUNError">Please enter a valid username</div>
        <div class="nCompletionValidationErrorMessage invisible nCompletionUNServerError">Unfortunately the username is taken</div>

        <div class="nCompletionBox">
            <div class="nCompletionBoxFirst nCompletionBoxFirstGender invisible">
                <div class="nCompletionIcon nCompletionIconGender"></div>
                <div class="nCompletionName">Gender</div>

            </div>
            <div class="nCompletionBoxSecond ">
                <div class="nCompletionIcon nCompletionIconGender"></div>
                <div class="nCompletionName">Gender</div>
                <div class="nCompletionArrowGender nSIRowEnterArrow nCompletionArrow nValidatorButton invisible"></div>
                <div class="nCompletionStatus"></div>
                <!-- <div class="nCompletionDropdown"> -->
                <div class="nCompletionInput">
                    <asp:DropDownList class="nCompletionTextInput nCompletionInputGender" ID="DropDownListGender" runat="server" data-role="none">
                        <asp:ListItem Value="0">Select</asp:ListItem>
                        <asp:ListItem Value="2">Female</asp:ListItem>
                        <asp:ListItem Value="1">Male</asp:ListItem>
                        <asp:ListItem Value="3">Other</asp:ListItem>
                    </asp:DropDownList>
                </div>
            </div>
        </div>
        <div class="nCompletionValidationErrorMessage invisible nCompletionGenderError">Please choose your gender</div>
        <div class="nCompletionBox">
            <div class="nCompletionBoxFirst nCompletionBoxFirstBD invisible">
                <div class="nCompletionIcon nCompletionIconBD"></div>
                <div class="nCompletionName">Birth Date</div>

            </div>
            <div class="nCompletionBoxSecond ">
                <div class="nCompletionIcon nCompletionIconBD"></div>
                <div class="nCompletionName">Birth Date</div>
                <div class="nCompletionArrowBD nSIRowEnterArrow nCompletionArrow nValidatorButton invisible"></div>
                <div class="nCompletionStatus"></div>
                <div class="nCompletionInput">
                    <input type="date" name="date" id="date" value="" data-role="none" class="nCompletionDateInput" />
                </div>
            </div>
        </div>
        <div class="nCompletionValidationErrorMessage invisible nCompletionBDError">Please set your birthdate</div>
        <div class="nCompletionValidationErrorMessage invisible nCompletionBDadultError">Sorry, you should be 18+ to use this app.</div>
        <div class="nCompletionValidationErrorMessage invisible nCompletionBDfutureError">Are you sure your age is minus?</div>
        <div class="nCompletionBox" style="height: 5.5em">
            <div class="nCompletionBoxFirst nCompletionBoxFirstLocation nCompletionBoxFirstLocation invisible">
                <div class="nCompletionIcon nCompletionIconLocation"></div>
                <div class="nCompletionName">Location</div>

            </div>
            <div class="nCompletionBoxSecond nCompletionBoxSecondLocation ">
                <div class="nCompletionIcon nCompletionIconLocation"></div>
                <div class="nCompletionName">
                    <label for="flip-1" class="nCompletionLocationFlipLabel">Location</label>
                </div>
                <div class="nCompletionArrowLocation nSIRowEnterArrow nCompletionArrow nValidatorButton invisible"></div>
                <div class="nCompletionStatus"></div>
                <div class="nCompletionLocationContainer">
                    <!--<div class="nCompletionLocationFlipContainer">
                    <select name="flip-1" class="nCompletionLocationFlip" data-role="slider" data-mini="true">
                        <option value="off">Off</option>
                        <option value="on">On</option>
                    </select>
                </div>
                -->
                    
                    <div class="nCompletionInput nCompletionInputLocationContainer">
                        <asp:DropDownList ID="DropDownListCountry" runat="server" AutoPostBack="False" OnSelectedIndexChanged="DropDownListCountry_SelectedIndexChanged" data-role="none" CssClass="nCompletionLocationInput nCompletionLocationInputCountry nCompletionTextInput">
                        </asp:DropDownList>
                    </div>
                    <div class="clear"></div>
                    <div class="nCompletionInput nCompletionInputLocationContainer">
                        <asp:DropDownList ID="DropDownListCity" runat="server" data-role="none" CssClass="nCompletionLocationInput nCompletionLocationLastInput">
                            <asp:ListItem Value="0">Select City</asp:ListItem>
                        </asp:DropDownList>
                    </div>
                    <div class="clear"></div>
                    <asp:TextBox ID="TextBoxRequestLocationCountry" CssClass="nCompletionNewCountry invisible" placeholder="country" runat="server" data-role="none"></asp:TextBox>
                    <div class="clear"></div>
                    <asp:TextBox ID="TextBoxRequestLocationCity" CssClass="nCompletionNewCity invisible" placeholder="city" runat="server" data-role="none"></asp:TextBox>
                    <div class="nCompletionNotListedButton nSearchChange">Not listed yet? Click here!</div>
                    <div class="nCompletionListedButton nSearchChange invisible">Go back to lists</div>
                </div>
            </div>
        </div>
        <div class="nCompletionValidationErrorMessage invisible nCompletionLocationError">Please choose your location</div>
        <div class="nCompletionValidationErrorMessage invisible nCompletionNewLocationError">Please enter new locations properly</div>
        <div class="nCompletionValidationErrorMessage nCompletionValidationErrorMessageBackEnd  nCompletionUNError invisible">&nbsp<asp:Label ID="LabelMessage" runat="server" Visible="false"></asp:Label></div>
        <br />
        <div class="nCompletionErrorMessage"></div>
        <div class="invisible">
            <asp:HiddenField ID="HiddenFieldDOB" runat="server" />
            <asp:Button ID="ButtonSubmit" runat="server" Text="Save Changes" OnClick="ButtonSubmit_Click" />
            <asp:FileUpload ID="FileUpload1" runat="server" onchange="readURL(this);" />
            <asp:HiddenField ID="HiddenFieldHasPhoto" runat="server" Value="false" />
            <asp:HiddenField ID="HiddenFieldPhotoUrl" runat="server" />
            <asp:HiddenField ID="HiddenFieldLocationStatus" runat="server" Value="1" />
            <asp:HiddenField ID="HiddenFieldLocationId" runat="server" />

        </div>
        <div class="nExploreFooter nThickFooter">
            <div class="nFooterButton nProfileMessageButton nValidatorButton">
                <div class="nFooter1Image nProfileImageGrey"></div>
                &nbsp CONTINUE</div>
        </div>


        <!--<asp:Label ID="LabelFirstName" runat="server" Text="First Name:" AssociatedControlID="TextBoxFirstName"></asp:Label>
    <asp:Label ID="LabelLastName" runat="server" AssociatedControlID="TextBoxLastName" Text="Last Name:"></asp:Label>
    <asp:Label ID="LabelUsername" runat="server" AssociatedControlID="TextBoxUsername" Text="Username:"></asp:Label>
    <asp:Label ID="LabelGender" runat="server" AssociatedControlID="DropDownListGender" Text="Gender:"></asp:Label>
    <asp:Label ID="LabelBirthdate" runat="server" Text="Birthdate:"></asp:Label>
    <asp:Label ID="LabelLocation" runat="server" Text="Current Location:"></asp:Label>
    -->
    </div>
</asp:Content>
