<%@ Page Title="Modify Event" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="EventsModify.aspx.cs" Inherits="WebApplication1.EventsModify" EnableEventValidation="false" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            eventsModifyPage();
            generalLook();
            menu();
        });
    </script>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle">Modify Event</div>
    </div>

    <!-- first page -->
    <div class="nAEPage invisible">
        <div>
            <div class="nContentTitle nEAContentTitle">Basic Information</div>
            <div class="nEventsAddDots">
                <div class="nOrangeEllipse"></div>
                <div class="nGreyEllipse"></div>
            </div>
        </div>
        <br />
        <br />
        <div class="clear"></div>
        <asp:Literal ID="LiteralMessage" runat="server" Visible="False"></asp:Literal>
        <div class="nEAContentHolder">
            <div class="nLeft">Type</div>
            <div class="nEAACtivityType nRight"></div>
            <div class="clear"></div>
            <div class="nEAAType">
                <div class="nActivityLogoContainer">
                    <div class="nActivityLogo nActivityTheater animationAll" data="Art / culture" activity-id="1"></div>
                </div>
                <div class="nActivityLogoContainer">
                    <div class="nActivityLogo nActivityBook animationAll " data="Education" activity-id="2"></div>
                </div>
                <div class="nActivityLogoContainer">
                    <div class="nActivityLogo nActivityDance animationAll" data="Entertainment" activity-id="3"></div>
                </div>
                <div class="nActivityLogoContainer">
                    <div class="nActivityLogo nActivityRestaurant animationAll" data="Food/drink" activity-id="4"></div>
                </div>
                <div class="nActivityLogoContainer">
                    <div class="nActivityLogo nActivityNature animationAll" data="Outdoor" activity-id="5"></div>
                </div>
                <div class="nActivityLogoContainer">
                    <div class="nActivityLogo nActivityShopping animationAll" data="Shopping" activity-id="6"></div>
                </div>
                <div class="nActivityLogoContainer">
                    <div class="nActivityLogo nActivitySport animationAll" data="Sports" activity-id="7"></div>
                </div>
                <div class="nActivityLogoContainer">
                    <div class="nActivityLogo nActivityMore animationAll" data="Others" activity-id="8"></div>
                </div>
            </div>
        </div>
        <div class="clear"></div>
        <hr />
        <div class="nEAContentHolder">
            <div>Name</div>
            <asp:TextBox ID="TextBoxName" MaxLength="50" runat="server" required="required" CssClass="nRedPlaceHolder nTextInput" data-role="none"></asp:TextBox>
        </div>
        <hr />
        <div class="nEAContentHolder">
            <div class="nLeft">Participants</div>
            <div class="clear"></div>
            <div class="participantsSliderContainer"></div>
            <!-- <input class="participantsSlider" type="range" name="slider-fill" id="slider-fill" value="1" min="1" max="100" data-highlight="true" /> -->
        </div>
        <!-- <div class="nEAParticipantsError nGeneralErrorMessage"></div> -->
        <div class="clear"></div>
        <hr />
        <div class="nEAContentHolder">
            <label class="nEAeachLable" for="ContentPlaceHolder1_TextBoxDate">Date</label>
            <div class="nEADateMessage"></div>
            <div class="clear"></div>
            <!-- m/d/y -->
            <asp:TextBox ID="TextBoxDate" MaxLength="20" type="date" runat="server" CssClass="nEAdate nTextInput" data-role="none"></asp:TextBox>
        </div>
        <div class="clear"></div>
        <hr />
        <div class="nEAContentHolder">
            <div class="nLeft nEAeachLable">Time</div>
            <div class="nEATimeMessage"></div>
            <div class="clear"></div>
            <input type="time" name="date" class="nEAtime nTextInput" data-mini="true" data-role="none" />
            <div class="nTimeAlternateContainer invisible">
                <div class="nTimeAlternateHour">
                    <select class="nTimeAlternateHourSelect" data-role="none">
                        <option value="01">01</option>
                        <option value="02">02</option>
                        <option value="03">03</option>
                        <option value="04">04</option>
                        <option value="05">05</option>
                        <option value="06">06</option>
                        <option value="07">07</option>
                        <option value="08">08</option>
                        <option value="09">09</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                    </select>
                </div>
                <div class="nTimeAlternateMin">
                    <select class="nTimeAlternateMinSelect" data-role="none">
                        <option value="00">00</option>
                        <option value="05">05</option>
                        <option value="10">10</option>
                        <option value="15">15</option>
                        <option value="20">20</option>
                        <option value="25">25</option>
                        <option value="30">30</option>
                        <option value="35">35</option>
                        <option value="40">40</option>
                        <option value="45">45</option>
                        <option value="50">50</option>
                        <option value="55">55</option>
                    </select>
                </div>
                <div class="nTimeAlternateAMPM">
                    <select class="nTimeAlternateAMPMSelect" data-role="none">
                        <option value="AM">AM</option>
                        <option value="PM">PM</option>
                    </select>
                </div>
            </div>
        </div>
        <br />
        <div class="nEAFirstPageError nGeneralErrorMessage"></div>
    </div>

    <!-- second page  -->
    <div class="nAEPage invisible">
        <div>
            <div class="nContentTitle nEAContentTitle">Finalizing</div>
            <div class="nEventsAddDots">
                <div class="nGreyEllipse"></div>
                <div class="nOrangeEllipse"></div>
            </div>
        </div>
        <br />
        <br />
        <div class="clear"></div>
        <div class="nEAContentHolder">
            <label for="ContentPlaceHolder1_DropDownListCountry" class="nEAeachLable">Location</label>
            <asp:DropDownList ID="DropDownListCountry" runat="server" AutoPostBack="False" data-mini="true" data-theme="b"
                OnSelectedIndexChanged="DropDownListCountry_SelectedIndexChanged" data-role="none" CssClass="nTextInput">
                <asp:ListItem Value="0">Select Country</asp:ListItem>
            </asp:DropDownList>
            <br />
            <br />
            <asp:DropDownList ID="DropDownListCity" data-mini="true" runat="server" data-theme="b" data-role="none" CssClass="nTextInput">
                <asp:ListItem Value="0">Select City</asp:ListItem>
            </asp:DropDownList>
            <div class="nEALocationMessage nGeneralErrorMessage"></div>
            <div class="clear"></div>
        </div>
        <div class="nEAContentHolder">
            <br />
            <label for="TextBoxAddress" class="nEAeachLable">Street Address</label>
            <br />
            <asp:TextBox ID="TextBoxAddress" MaxLength="40" runat="server" data-role="none" CssClass="nTextInput"></asp:TextBox>
            <div class="clear"></div>
        </div>
        <hr />
        <div class="nEAContentHolder">
            <label for="ContentPlaceHolder1_TextBoxDescriptions">Description</label>
            <!-- <div class="nEAACtivityType nRight">1</div> -->
            <div class="clear"></div>
            <asp:TextBox ID="TextBoxDescriptions" CssClass="nEventsAddDesc nTextInput" runat="server" TextMode="MultiLine" data-role="none"></asp:TextBox>
            <br />
        </div>
        <div class="nEAContentHolder">
               <label>Choose the event's cover</label>
                <div class="nSPCoverHolder">
                    <div class="nSPCoverPhoto" activity-id="101">
                        <!-- <div class="nSPCoverPhotoTransparent"></div> -->
                    </div>
                </div>
                <br />
                <div class="nEALogosContainer">
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="101"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="102"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="103"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="104"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="201"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="202"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="203"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="301"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="302"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="303"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="304"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="401"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="402"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="403"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="404"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="405"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="406"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="501"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="502"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="503"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="504"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="505"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="506"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="601"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="701"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="702"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="703"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="704"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="705"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="706"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="707"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="708"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="709"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="710"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="711"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="801"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="802"></div>
                    </div>
                    <div class="nSearchLogoContainer nSPLogoContainer ">
                        <div class="nSearchLogo nSPLogo" activity-id="803"></div>
                    </div>
                </div>
            <div class="invisible">
                <asp:Button ID="Button1" runat="server" OnClick="ButtonSubmit_Click" Text="Add" />
            </div>
        </div>
    </div>
    <!--third page -->
    <div class="nAEPage invisible">
        <div>
            <div class="nContentTitle nEAContentTitle">Location</div>
            <div class="nEventsAddDots">
                <div class="nGreyEllipse"></div>
                <div class="nGreyEllipse"></div>
                <div class="nOrangeEllipse"></div>
                <div class="nGreyEllipse"></div>
                <div class="nGreyEllipse"></div>
            </div>
        </div>
        <div class="clear"></div>
        <hr />

        <br />

    </div>

    <!-- Fourth page  -->
    <div class="nAEPage invisible">
        <div>
            <div class="nContentTitle nEAContentTitle">Cover photo</div>
            <div class="nEventsAddDots">
                <div class="nGreyEllipse"></div>
                <div class="nGreyEllipse"></div>
                <div class="nGreyEllipse"></div>
                <div class="nOrangeEllipse"></div>
                <div class="nGreyEllipse"></div>
            </div>
        </div>
        <div class="clear"></div>
        <hr />
        <div class="nEAContentHolder">
            <div class="nLeft">Languages</div>
            <div class="nRight nEAlanguagesAll">
                <div class="nEAlanguageButtons nEAlanguageButtonsAdd">
                    <div class="nEAlanguageButtonsPlus">+</div>
                    <div class="clear"></div>
                    <div class="nDotsBox nDotBoxLinks">
                        <div class="nDotsBoxEach" data-language="EN">English</div>
                        <div class="nDotsBoxEach" data-language="AR">Arabic</div>
                        <div class="nDotsBoxEach" data-language="FA">Farsi</div>
                        <div class="nDotsBoxEach" data-language="FI">Finnish</div>
                        <div class="nDotsBoxEach" data-language="FR">French</div>
                        <div class="nDotsBoxEach" data-language="DE">German</div>
                        <div class="nDotsBoxEach" data-language="HI">Hindi</div>
                        <div class="nDotsBoxEach" data-language="IT">Italian</div>
                        <div class="nDotsBoxEach" data-language="JA">Japanese</div>
                        <div class="nDotsBoxEach" data-language="PL">Polish</div>
                        <div class="nDotsBoxEach" data-language="PT">Portuguese</div>
                        <div class="nDotsBoxEach" data-language="RU">Russian</div>
                        <div class="nDotsBoxEach" data-language="ES">Spanish</div>
                        <div class="nDotsBoxEach" data-language="SV">Swedish</div>
                        <div class="nDotsBoxEach" data-language="TR">Turkish</div>
                    </div>
                </div>

            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
        <hr />

        <!--  <div class="nEAContentHolder">
            <div class="nLeft">public</div>
            <div class="nRight">
                <asp:DropDownList ID="DropDownListPrivacy" runat="server" data-role="slider" data-mini="true">
                    <asp:ListItem Value="2">No</asp:ListItem>
                    <asp:ListItem Value="1" Selected="selected">Yes</asp:ListItem>
                </asp:DropDownList>
            </div>
            <div class="clear"></div>

            <div class="clear"></div>
        </div>
        <hr />
      -->

    </div>

    <!-- Fifth page-->
    <div class="nAEPage invisible">
        <div>
            <div class="nContentTitle nEAContentTitle">Cover photo</div>
            <div class="nEventsAddDots">
                <div class="nGreyEllipse"></div>
                <div class="nGreyEllipse"></div>
                <div class="nGreyEllipse"></div>
                <div class="nGreyEllipse"></div>
                <div class="nOrangeEllipse"></div>
            </div>
        </div>
        <div class="clear"></div>
        <hr />

    </div>

    <div class="nExploreFooter nThickFooter">
        <div class="nProfileFooterContainer nProfileFooterContainerOneButton ">
            <div class="nFooterButton nProfileMessageButton nProfileNextButton">
                <div class="nFooter1Image nProfileImageGrey"></div>
                &nbsp Next
            </div>
        </div>
        <div class="nProfileFooterContainer nProfileFooterContainerTwoButton invisible">
            <div class="nFooterButton nNotButton">
                <div class="nFooter1Image nProfileImageOrange"></div>
                <span>&nbsp Previous</span>
            </div>
            <div class="nFooterButton nRequestButton nProfileNextButton">
                <div class="nFooter1Image nProfileImageGreen"></div>
                <span>&nbsp Next</span>
            </div>
        </div>
    </div>

    <div class="invisible">
        <asp:Panel ID="PanelInfo" runat="server">
            <asp:Label ID="LabelName" runat="server" Text="Event Name:"></asp:Label>
            <asp:Label ID="LabelDate" runat="server" Text="Date:"></asp:Label>

            <asp:Label ID="LabelTime" runat="server" Text="Time:"></asp:Label>
            <asp:DropDownList ID="DropDownListTimeHour" runat="server">
                <asp:ListItem Value="H">Hour</asp:ListItem>
                <asp:ListItem Value="1">1</asp:ListItem>
                <asp:ListItem Value="2">2</asp:ListItem>
                <asp:ListItem Value="3">3</asp:ListItem>
                <asp:ListItem Value="4">4</asp:ListItem>
                <asp:ListItem Value="5">5</asp:ListItem>
                <asp:ListItem Value="6">6</asp:ListItem>
                <asp:ListItem Value="7">7</asp:ListItem>
                <asp:ListItem Value="8">8</asp:ListItem>
                <asp:ListItem Value="9">9</asp:ListItem>
                <asp:ListItem Value="10">10</asp:ListItem>
                <asp:ListItem Value="11">11</asp:ListItem>
                <asp:ListItem Value="12">12</asp:ListItem>
                <asp:ListItem Value="13">13</asp:ListItem>
                <asp:ListItem Value="14">14</asp:ListItem>
                <asp:ListItem Value="15">15</asp:ListItem>
                <asp:ListItem Value="16">16</asp:ListItem>
                <asp:ListItem Value="17">17</asp:ListItem>
                <asp:ListItem Value="18">18</asp:ListItem>
                <asp:ListItem Value="19">19</asp:ListItem>
                <asp:ListItem Value="20">20</asp:ListItem>
                <asp:ListItem Value="21">21</asp:ListItem>
                <asp:ListItem Value="22">22</asp:ListItem>
                <asp:ListItem Value="23">23</asp:ListItem>
            </asp:DropDownList>

            <asp:DropDownList ID="DropDownListTimeMinute" runat="server">
                <asp:ListItem Value="M">Minute</asp:ListItem>
                <asp:ListItem Value="0">0</asp:ListItem>
                <asp:ListItem Value="1">1</asp:ListItem>
                <asp:ListItem Value="2">2</asp:ListItem>
                <asp:ListItem Value="3">3</asp:ListItem>
                <asp:ListItem Value="4">4</asp:ListItem>
                <asp:ListItem Value="5">5</asp:ListItem>
                <asp:ListItem Value="6">6</asp:ListItem>
                <asp:ListItem Value="7">7</asp:ListItem>
                <asp:ListItem Value="8">8</asp:ListItem>
                <asp:ListItem Value="9">9</asp:ListItem>
                <asp:ListItem Value="10">10</asp:ListItem>
                <asp:ListItem Value="11">11</asp:ListItem>
                <asp:ListItem Value="12">12</asp:ListItem>
                <asp:ListItem Value="13">13</asp:ListItem>
                <asp:ListItem Value="14">14</asp:ListItem>
                <asp:ListItem Value="15">15</asp:ListItem>
                <asp:ListItem Value="16">16</asp:ListItem>
                <asp:ListItem Value="17">17</asp:ListItem>
                <asp:ListItem Value="18">18</asp:ListItem>
                <asp:ListItem Value="19">19</asp:ListItem>
                <asp:ListItem Value="20">20</asp:ListItem>
                <asp:ListItem Value="21">21</asp:ListItem>
                <asp:ListItem Value="22">22</asp:ListItem>
                <asp:ListItem Value="23">23</asp:ListItem>
                <asp:ListItem Value="24">24</asp:ListItem>
                <asp:ListItem Value="25">25</asp:ListItem>
                <asp:ListItem Value="26">26</asp:ListItem>
                <asp:ListItem Value="27">27</asp:ListItem>
                <asp:ListItem Value="28">28</asp:ListItem>
                <asp:ListItem Value="29">29</asp:ListItem>
                <asp:ListItem Value="30">30</asp:ListItem>
                <asp:ListItem Value="31">31</asp:ListItem>
                <asp:ListItem Value="32">32</asp:ListItem>
                <asp:ListItem Value="33">33</asp:ListItem>
                <asp:ListItem Value="34">34</asp:ListItem>
                <asp:ListItem Value="35">35</asp:ListItem>
                <asp:ListItem Value="36">36</asp:ListItem>
                <asp:ListItem Value="37">37</asp:ListItem>
                <asp:ListItem Value="38">38</asp:ListItem>
                <asp:ListItem Value="39">39</asp:ListItem>
                <asp:ListItem Value="40">40</asp:ListItem>
                <asp:ListItem Value="41">41</asp:ListItem>
                <asp:ListItem Value="42">42</asp:ListItem>
                <asp:ListItem Value="43">43</asp:ListItem>
                <asp:ListItem Value="44">44</asp:ListItem>
                <asp:ListItem Value="45">45</asp:ListItem>
                <asp:ListItem Value="46">46</asp:ListItem>
                <asp:ListItem Value="47">47</asp:ListItem>
                <asp:ListItem Value="48">48</asp:ListItem>
                <asp:ListItem Value="49">49</asp:ListItem>
                <asp:ListItem Value="50">50</asp:ListItem>
                <asp:ListItem Value="51">51</asp:ListItem>
                <asp:ListItem Value="52">52</asp:ListItem>
                <asp:ListItem Value="53">53</asp:ListItem>
                <asp:ListItem Value="54">54</asp:ListItem>
                <asp:ListItem Value="55">55</asp:ListItem>
                <asp:ListItem Value="56">56</asp:ListItem>
                <asp:ListItem Value="57">57</asp:ListItem>
                <asp:ListItem Value="58">58</asp:ListItem>
                <asp:ListItem Value="59">59</asp:ListItem>
            </asp:DropDownList>
            <asp:CheckBox ID="CheckBoxTimeUnknown" runat="server" Text="Unknown" />
            <asp:Label ID="LabelParticipants" runat="server" Text="Participants:"></asp:Label>
            <asp:TextBox ID="TextBoxParticipants" runat="server">1</asp:TextBox>
            -->
            <asp:Label ID="LabelLocation" runat="server" Text="Location:"></asp:Label>


            <asp:Label ID="LabelType" runat="server" Text="Type:"></asp:Label>
            <asp:Label ID="LabelLanguages" runat="server" Text="Languages:"></asp:Label>
            <asp:TextBox ID="TextBoxLanguages" runat="server"></asp:TextBox>
            <asp:Label ID="LabelDescriptions" runat="server" Text="Descriptions:"></asp:Label>


            <asp:Button ID="ButtonDelete" runat="server" OnClick="ButtonDelete_Click" Text="Delete" />
            <asp:Button ID="ButtonSubmit" runat="server" OnClick="ButtonSubmit_Click" Text="Modify" />
            <asp:LinkButton ID="LinkButtonAdvance" runat="server" OnClick="LinkButtonAdvance_Click">Show Advance</asp:LinkButton>
            <asp:Panel ID="PanelAdvance" runat="server" Visible="False">
            </asp:Panel>
            <asp:HiddenField ID="HiddenFieldAdvance" runat="server" Value="0" />
        </asp:Panel>
        <asp:HiddenField ID="HiddenFieldParticipants" runat="server" />
        <asp:HiddenField ID="HiddenFieldParticipantsAccepted" runat="server" />
        <asp:HiddenField ID="HiddenFieldDate" runat="server" />
        <asp:HiddenField ID="HiddenFieldLanguages" runat="server" />
        <asp:HiddenField ID="HiddenFieldTypeId" runat="server" />
        <asp:HiddenField ID="HiddenFieldStep" runat="server" />
        <asp:HiddenField ID="HiddenFieldCoverId" runat="server" />
        <asp:HiddenField ID="HiddenFieldLocationId" runat="server" />
    </div>
</asp:Content>

