<%@ Page Title="Explore" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Explore.aspx.cs" Inherits="WebApplication1.Explore" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            eventsView();
            explorePage();
            generalLook();
            menu();
        });
    </script>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle" id="demo">Explore</div>
    </div>

    <!-- no events to explore -->
    <!-- displaying error like done page -->
    <div class="pageErrorContent invisible">
        <div class="nDoneSmiley">:)</div>
        <div class="nDoneMessage">Message</div>
        <div class="nDoneAllButtons">
            <div class="nDoneButton nDoneButton4 invisible">
                <div class="nDoneImage nDoneImage4"></div>
                <div class="nDoneInsideImage nDoneInsideImage4"></div>
                <div class="nDoneText nDoneText4">4</div>
            </div>
            <div class="nDoneButton nDoneButton3 invisible">
                <div class="nDoneImage nDoneImage3"></div>
                <div class="nDoneInsideImage nDoneInsideImage3"></div>
                <div class="nDoneText nDoneText3">3</div>
            </div>
            <div class="nDoneButton nDoneButton2 invisible">
                <div class="nDoneImage nDoneImage2"></div>
                <div class="nDoneInsideImage nDoneInsideImage2"></div>
                <div class="nDoneText nDoneText2">2</div>
            </div>
            <div class="nDoneButton nDoneButton1 invisible">
                <div class="nDoneImage nDoneImage1"></div>
                <div class="nDoneInsideImage nDoneInsideImage1"></div>
                <div class="nDoneText nDoneText1">1</div>
            </div>
        </div>
    </div>
    <div class="pageNormalContent invisible">
        <div class="nContentCover">
            <div class="nContentCoverTransparent ">
                <div class="nContentTitle">
                    <b>
                        <asp:Label ID="LabelEventName" runat="server"></asp:Label>
                    </b>

                    <!--<asp:Label ID="Label2" runat="server"></asp:Label> -->

                </div>
                <!-- <div class="nDots"><i class="fa fa-ellipsis-h"></i>&nbsp</div> -->
                <div class="nDots nDotsEvent">
                    <i class="fa fa-ellipsis-h nDotsLogo"></i>
                    <div class="clear"></div>
                    <div class="nDotsBox nDotBoxLinks">
                        <div class="nDotsBoxEachLogo nDotsBoxEachLogoShare"></div>
                        <div class="nDotsBoxEach">Share</div>
                        <div class="nDotsBoxEachLogo nDotsBoxEachLogoBookmark"></div>
                        <div class="nDotsBoxEach nEVbookmarkButton">Bookmark</div>
                        <div class="nDotsBoxEachLogo nDotsBoxEachLogoReport"></div>
                        <div class="nDotsBoxEach">Report user</div>
                    </div>
                    <div class="nDotsBox nDotsBoxShare hide">
                        <a class="nEVShareButtonFB" target="_blank" href="#">
                            <img class="nEVshareImg" src="../Images/Icons/fb.png" alt="facebook" width="32" height="32" /></a>
                        <a class="nEVShareButtonTwitter" target="_blank" href="#">
                            <img class="nEVshareImg" src="../Images/Icons/twitter.png" alt="facebook" width="32" height="32" /></a>
                    </div>
                </div>
                <div class="clear"></div>
                <span class="nEVBy">by</span>
                <span class="nEVEventName"></span>

                <div class="clear"></div>
                <div class="nEventCoverBox">
                    <div class="nRoundPicture nActivityPicture">
                    </div>
                </div>
                <div class="nEventCoverBox">
                    <div class="nRoundPicture nEVOwnerPicture">
                        <canvas id="canvas2" width="115" height="115"></canvas>
                    </div>
                </div>
                <div class="nEventCoverBox">
                    <div class="nRoundPicture nParticipantNumberPicture">
                        <div class="nParticipantNumberPictureTop">
                            <asp:Label ID="LabelParticipantsAvailable" runat="server"></asp:Label>/<asp:Label ID="LabelParticipants" runat="server"></asp:Label>
                            <canvas id="EVcanvas" width="115" height="115"></canvas>
                        </div>
                        <div class="nParticipantNumberPictureBot">
                            <b>
                                <!-- <asp:Label ID="Label5" runat="server"></asp:Label> -->
                            </b>
                        </div>
                    </div>
                    <!-- old graphs
                <div class="nRoundPicture nNewGraph">
                    <div class="nNewGraphTop"></div>
                    <div class="nNewGraphBottom"></div>
                    <div class="nNewGraphText">
                        <b>
                            1</b> participant needed (<span class="nParticipantAvailable"></span>/3)
                    </div>
                </div>
                    -->
                </div>
            </div>
        </div>
        <div class="nTimeAndLocation nEVTimeAndLocation">
            <div class="nExploreLocation nEVLocation">
                <i class="fa fa-map-marker"></i>&nbsp
                    <asp:Label ID="LabelLocation" runat="server"></asp:Label>
            </div>
            <div class="nExploreTime nEVTime">
                <i class="fa fa-clock-o"></i>&nbsp<span class="nEVdate">Time unknown</span>
            </div>
        </div>
        <div class="nEVTabbedContent">
            <div class="nTabsHolder">
                <div class="nTabs nTabs2 nExploreSelected" ntabnumber="1">
                    <b>DESCRIPTION</b>
                </div>
                <div class="nTabs nTabs2" ntabnumber="2">
                    <b>MAP</b>
                </div>
            </div>
            <div class="nExploreContentHolder">
                <!-- description -->
                <div class="nDescriptionContent nTabContents">
                    <asp:Label ID="LabelAddress" runat="server"></asp:Label><br />
                    <asp:Label ID="LabelDescriptions" runat="server"></asp:Label>
                </div>
                <!-- map -->
                <div class="nParticipantMap nTabContents nEVTabContents hidden">
                    <div id="map_canvas"></div>
                </div>
                <!-- board -->
                <div class="nBoardContent nTabContents hidden">
                    <asp:Panel ID="PanelBoardMessageAdd" runat="server">
                        <asp:TextBox ID="TextBoxBoardMessageAdd" CssClass="TextBoxMultiR2L" TextMode="MultiLine" data-autogrow="false" runat="server"></asp:TextBox>
                    </asp:Panel>
                    <asp:Repeater ID="RepeaterBoardMessages" runat="server">
                        <ItemTemplate>
                            <div class="MessageSender">
                                <asp:HiddenField ID="HiddenFieldSenderName" runat="server" Value='<%# Eval("SenderName") %>' />
                            </div>
                            <div class="eachMessage">
                                <div class="nMessagesPicture nMessagesShowPicture">
                                    <asp:HiddenField ID="HiddenFieldProfilePicUrl" runat="server" Value='<%# Eval("ProfilePicUrl") %>' />
                                </div>
                                <asp:HiddenField ID="HiddenFieldMessageId" runat="server" Value='<%# Eval("MessageId") %>' />

                                <div class="nMessageBody nEventsMessage">
                                    <span><%# Eval("Message") %></span>
                                    <div class="nMessageDecoration"></div>
                                </div>

                                <div>
                                </div>
                                <div class="invisible">
                                    each message sender lable
                                </div>
                            </div>
                            <div class="clear"></div>
                            <div class="MessageListDate nMSDate">
                                <!-- <asp:Label ID="LabelDate" runat="server" Text='<%# Eval("PassedDate") %>' CssClass="EachMessageDate ViewClass"></asp:Label> -->
                            </div>
                            <div class="clear"></div>

                            <asp:HiddenField ID="HiddenFieldIsOwner" runat="server" Value='<%# Eval("IsOwner") %>' />
                            <asp:HiddenField ID="HiddenFieldSenderId" runat="server" Value='<%# Eval("SenderId") %>' />

                            <asp:HiddenField ID="HiddenField1" runat="server" Value='<%# Eval("ProfilePicUrl") %>' />
                        </ItemTemplate>
                    </asp:Repeater>

                </div>
                <!-- participants -->
                <div class="nParticipantsContent nTabContents hidden">
                    <asp:Label ID="LabelNoRecord" runat="server" Text="No participants yet!" Visible="False"></asp:Label>
                    <asp:Repeater ID="RepeaterParticipants" runat="server">
                        <ItemTemplate>
                            <div class="nMessagesPicture nEVMessagesPicture">
                                <asp:HiddenField ID="HiddenFieldProfilePicUrl" runat="server" Value='<%# Eval("ProfilePicUrl") %>' />
                            </div>
                            <asp:HyperLink ID="HyperLinkParticipant" runat="server" NavigateUrl='<%#"~/Profile/"+ Eval("UserId") %>' CssClass="nEVparticipantName nNoDecoration"><%#Eval("FirstName") + " " + Eval("LastName") %></asp:HyperLink>
                        </ItemTemplate>
                    </asp:Repeater>
                </div>

            </div>
        </div>
        <div class="hiddenButtons">
        </div>
        <div class="invisible">
            <!-- these are all empty -->
            <asp:HyperLink ID="HyperLinkModify" runat="server" Visible="False">Modify event</asp:HyperLink>
            <asp:Label ID="LabelLanguages" runat="server"></asp:Label>
            <asp:Label ID="LabelStatus" runat="server"></asp:Label>
            <asp:Button ID="ButtonBookmark" runat="server" OnClick="ButtonBookmark_Click" Text="Bookmark" />
            <asp:Label ID="LabelMessage" runat="server"></asp:Label>
            <asp:Button ID="ButtonActionYes" runat="server" OnClick="ButtonActionYes_Click" />
            <asp:Button ID="ButtonActionNo" runat="server" OnClick="ButtonActionNo_Click" />
            -->
        </div>
        <div class="nExploreFooter nThickFooter">
            <div class="nEVRequestMessageError nGeneralErrorMessage invisible">Please enter the request message!</div>
            <div class="nEVRequestMessageContainer invisible">
                <asp:TextBox ID="TextBoxMessage" runat="server" CssClass="nEVRequestMessage" data-role="none" placeholder="type your message here" MaxLength="85"></asp:TextBox>
            </div>
            <div class="nFooterButton nNotButton">
                <div class="nFooter1Image nProfileImageOrange"></div>
                NOT INTERESTED
            </div>
            <div class="nFooterButton nRequestButton nExploreRequestButton">
                <div class="nFooter1Image nProfileImageGreen"></div>
                SEND REQUEST</div>
            <div class="nFooterButton nProfileMessageButton nExploreRequestButton nRequestButton invisible ">CONFIRM REQUEST</div>
        </div>
    </div>
    <asp:HiddenField ID="HiddenFieldOwnerId" runat="server" />
    <asp:HiddenField ID="HiddenFieldEventId" runat="server" />
    <asp:HiddenField ID="HiddenFieldDate" runat="server" />
    <asp:HiddenField ID="HiddenFieldOwnerRateScore" runat="server" />
    <asp:HiddenField ID="HiddenFieldOwnerPhotoUrl" runat="server" />
    <asp:HiddenField ID="HiddenFieldUsername" runat="server" />
    <asp:HiddenField ID="HiddenFieldOwnerFullname" runat="server" />
    <asp:HiddenField ID="HiddenFieldOwnerRateCount" runat="server" />
    <asp:HiddenField ID="HiddenFieldTypeId" runat="server" />
    <asp:HiddenField ID="HiddenFieldCoverId" runat="server" />

    <asp:HiddenField ID="HiddenFieldStatus" runat="server" />
    <asp:HiddenField ID="HiddenFieldTitle" runat="server" />
    <asp:HiddenField ID="HiddenFieldSmiley" runat="server" />
    <asp:HiddenField ID="HiddenFieldMessage" runat="server" />
    <asp:HiddenField ID="HiddenFieldLinksNumber" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink1Image" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink1Text" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink1Url" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink1Color" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink2Image" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink2Text" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink2Url" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink2Color" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink3Image" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink3Text" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink3Url" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink3Color" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink4Image" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink4Text" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink4Url" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink4Color" runat="server" />

</asp:Content>
