<%@ Page Title="Feedback" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Feedback.aspx.cs" Inherits="WebApplication1.Feedback" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            FeedbackPage();
            generalLook();
            menu();
        });
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle" id="demo">Feedback</div>
    </div>
    <div class="nDoneSmiley ">:)</div>
    <div class="nDoneMessage ">We are so excited to hear your feedback.</div>
    <br />
    <br />
    <div class="nFBEachOuterContainer " data-value="1">
        <div class="nFBEachContainer">
            <div class="nFBEachLogo">:((</div>
        </div>
        <div class="nFBEachText">awful</div>
    </div>
    <div class="nFBEachOuterContainer" data-value="2">
        <div class="nFBEachContainer">
            <div class="nFBEachLogo">:(</div>
        </div>
        <div class="nFBEachText">bad</div>
    </div>
    <div class="nFBEachOuterContainer" data-value="3">
        <div class="nFBEachContainer">
            <div class="nFBEachLogo">:|</div>
        </div>
        <div class="nFBEachText">so-so</div>
    </div>
    <div class="nFBEachOuterContainer" data-value="4">
        <div class="nFBEachContainer">
            <div class="nFBEachLogo">:)</div>
        </div>
        <div class="nFBEachText">good</div>
    </div>
    <div class="nFBEachOuterContainer nFBEachOuterContainerSelected" data-value="5">
        <div class="nFBEachContainer">
            <div class="nFBEachLogo">:D</div>
        </div>
        <div class="nFBEachText">awsome</div>
    </div>
    <div class="clear"></div>
    <br />
    <br />
    <div class="nDoneMessage ">Any comments to add?</div>
    <div class="nEAContentHolder">
        <asp:TextBox ID="TextBoxFeedback" runat="server" TextMode="MultiLine"></asp:TextBox>
    </div>
    <div class="invisible">
        <asp:Button ID="ButtonSubmit" runat="server" Text="Button" OnClick="ButtonSubmit_Click" />
    </div>
    <asp:HiddenField ID="HiddenFieldRate" runat="server" />
    <div class="nExploreFooter nThickFooter">
        <div class="nFooterButton nProfileMessageButton nRequestButton">
            <div class="nFooter1Image nProfileImageGreen">
            </div>
            SEND FEEDBACK
        </div>
    </div>
</asp:Content>
