<%@ Page Title="Invite" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Invite.aspx.cs" Inherits="WebApplication1.Invite" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            InvitePage();
            generalLook();
            menu();
        });
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd">
            <div class="nMenuAddIcon"></div>
        </div>
        <div class="nPageTitle">Invite</div>
    </div>
    <br />
    <div class="nInviteEachContainer nInviteEachContainerFB">
        <div class="nInviteLogo nInviteLogoFB">
        </div>
        <div class="nInviteButton nInviteButtonFB">
            Share the invitation link
        </div>
    </div>
    <div class="clear"></div>
    <hr class="nInviteButtonHr" />
    <div class="nInviteEachContainer nInviteEachContainerTwitter">
        <div class="nInviteLogo nInviteLogoTwitter">
        </div>
        <div class="nInviteButton nInviteButtonTwitter">
            Tweet the invitation link
        </div>
    </div>
    <div class="clear"></div>
    <hr class="nInviteButtonHr" />
    <div class="nInviteEachContainer nInviteEachContainerMail">
        <div class="nInviteLogo nInviteLogoMail">
        </div>
        <div class="nInviteButton nInviteButtonMail">
            Email the invitation link
        </div>
    </div>
    <div class="clear"></div>
    <div class="nInviteEmailOuterContainer invisible">
        <div class="nInviteEmailInnerContainer">
            <asp:TextBox ID="TextBoxEmail" runat="server" placeholder="Email address" type="email"></asp:TextBox>
        </div>
        <div class="nInviteEmailarrow"></div>
        <div class="clear"></div>
        <br />
        <div class="nGeneralErrorMessage"></div>
    </div>
    <div class="invisible">
        <asp:Button ID="ButtonSubmit" runat="server" OnClick="ButtonSubmit_Click" Text="Send" />
    </div>
    <asp:HiddenField ID="HiddenFieldUserId" runat="server" />

    <asp:HiddenField ID="HiddenFieldToastStatus" runat="server" Value="0" />
    <asp:HiddenField ID="HiddenFieldToastMode" runat="server" />
    <asp:HiddenField ID="HiddenFieldToastSmiley" runat="server" />
    <asp:HiddenField ID="HiddenFieldToastMessage" runat="server" />
    <asp:HiddenField ID="HiddenFieldButton1Text" runat="server" />
    <asp:HiddenField ID="HiddenFieldButton2Text" runat="server" />
    <asp:HiddenField ID="HiddenFieldButton1Color" runat="server" />
    <asp:HiddenField ID="HiddenFieldButton2Color" runat="server" />
    <asp:HiddenField ID="HiddenFieldButton1Url" runat="server" />
    <asp:HiddenField ID="HiddenFieldButton2Url" runat="server" />
</asp:Content>
