<%@ Page Title="Messages" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Messages.aspx.cs" Inherits="WebApplication1.Messages" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            generalLook();
            menu();
            messagesPage();
        });
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle">Messages</div>
    </div>
    <div class="nDoneSmiley invisible">:)</div>
    <div class="nDoneMessage invisible">There is no message to display.</div>
    <asp:Repeater ID="RepeaterMessages" runat="server">
        <ItemTemplate>
            <div class="fullNotificationContainer">
                <div class="nMessagesPicture">
                    <asp:HiddenField ID="HiddenFieldProfilePicUrl" runat="server" Value='<%# Eval("ProfilePicUrl") %>' />
                </div>
                <div class="nMessagesInsideDiv">
                    <div class="MessageSender">
                        <asp:HyperLink ID="HyperLinkSubject" runat="server" NavigateUrl='<%#"~/Messages/"+ Eval("OtherId") %>'><%#Eval("FirstName") + " " + Eval("LastName") %></asp:HyperLink>
                    </div>
                    <br />
                    <div class="MessageBody">
                        <asp:Label ID="LabelBeriefBody" runat="server" Text='<%# Eval("Brief", "{0}...") %>'></asp:Label>
                    </div>
                    <div class="nNotificationX nMessagesX">
                        x
                            <asp:HiddenField ID="HiddenFieldMessageListId" runat="server" Value='<%# Eval("MessageListId") %>' />
                    </div>
                    <div class="MessageListDate">
                        <div class="nSmallIcon nBlogClock nMessagesClock"></div>
                        <asp:Label ID="LabelDate" runat="server" Text='<%# Eval("PassedDate") %>'></asp:Label>
                    </div>
                </div>
                <div class="nMessagesNumberContainer hidden">
                    <div class="nMessagesUnreadNumber">
                        <asp:Label ID="LabelNewCount" runat="server" CssClass="nMessagesNewCount" Text='<%# Eval("NewCount") %>'></asp:Label>
                    </div>
                </div>
                <div class="clear"></div>
                <div class="invisible">
                    <div class="nMessagesImageDiv">
                    </div>
                    <asp:Image ID="ImagePhoto" runat="server" Height="60px" ImageUrl='<%# Eval("OtherId") %>' Width="60px" />
                    <asp:Label ID="LabelUnread" runat="server" CssClass="nMessagesNewBool" Text='<%# Eval("Unread") %>'></asp:Label>
                </div>
            </div>
            <hr class="nMessagesHr" />
        </ItemTemplate>
    </asp:Repeater>
    <asp:Label ID="LabelNoRecord" runat="server" Text="You have no messages!" Visible="False"></asp:Label><div class="nExploreFooter">
        <!--    <div class="nFooterButton nProfileMessageButton">WRITE A MESSAGE</div> -->
    </div>
    <asp:HiddenField ID="HiddenFieldMessageListIdDelete" runat="server" />
    <asp:HiddenField ID="HiddenFieldStatus" runat="server" />
    <div class="invisible">
        <asp:Button ID="ButtonDelete" runat="server" Text="Button" OnClick="ButtonDelete_Click" />
    </div>
</asp:Content>
