<%@ Page Title="Nearby" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Nearby.aspx.cs" Inherits="WebApplication1.Nearby" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            generalLook();
            menu();
            nearbyPage();
        });
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle">Nearby</div>
    </div>

    <div class="pageErrorContent invisible">
        <div class="nDoneSmiley">:)</div>
        <div class="nDoneMessage">Message</div>
        <div class="nDoneAllButtons">
            <div class="nDoneButton nDoneButton4 invisible">
                <div class="nDoneImage nDoneImage4"></div>
                <div class="nDoneText nDoneText4">4</div>
            </div>
            <div class="nDoneButton nDoneButton3 invisible">
                <div class="nDoneImage nDoneImage3"></div>
                <div class="nDoneText nDoneText3">3</div>
            </div>
            <div class="nDoneButton nDoneButton2 invisible">
                <div class="nDoneImage nDoneImage2"></div>
                <div class="nDoneText nDoneText2">2</div>
            </div>
            <div class="nDoneButton nDoneButton1 invisible">
                <div class="nDoneImage nDoneImage1"></div>
                <div class="nDoneText nDoneText1">1</div>
            </div>
        </div>
    </div>
    <br />
    <div class="nSearchLocation">
        <span class="nSearchLocationSpan nNearbyLocationSpan">Finland - Helsinki </span><span class="nSearchChange">&nbsp;(Change)</span>
    </div>
    <br />
    <div class="pageNormalContent pageNormalContentNearby invisible">
        <!-- city-->
        <!-- mode buttons -->

        <div class="nNearbyTimeButtonsContainer">
            <!--  1 all 2 day 3 week 4 month -->
            <div class="nNearbyTimeButtons nNearbyTimeButtons1 animationAll " data-mode="2">
                today
            </div>
            <div class="nNearbyTimeButtons nNearbyTimeButtons2 animationAll" data-mode="3">
                this week
            </div>
            <div class="nNearbyTimeButtons nNearbyTimeButtons3 animationAll" data-mode="4">
                this month
            </div>
            <div class="nNearbyTimeButtons nNearbyTimeButtons4 animationAll nNearbyTimeButtonsSelected" data-mode="1">
                All time
            </div>
        </div>
        <br />
        <div class="nNearbyEventsContainer animationAll">
        </div>
        <div class="nNearbyEventsContainerFooter invisible">
            <div class="nNearbyEventsContainerFooterButton">More</div>
        </div>
    </div>


    <!--  <asp:Repeater ID="RepeaterCity" runat="server">
            <ItemTemplate>
                <div class="nContentCover nNearbyCover">
                    <div class="invisible nFeedCoverId"><%# Eval("CoverId") %></div>
                    <div class="invisible nFeedEventId"><%# Eval("EventId") %></div>
                    <div class="invisible"><%# Eval("OwnerName") %></div>
                    <div class="invisible nFeedUserRate"><%# Eval("UserRate") %></div>
                    <div class="invisible nFeedParticipants"><%# Eval("Participants") %></div>
                    <div class="invisible nFeedParticipantsAvailable"><%# Eval("ParticipantsAccepted") %></div>
                    <div class="nContentCoverTransparent">
                        <div class="nContentTitle">
                            <!--<b><%# Eval("Name") %>
                                <!-- </b><span class="nEVBy">by</span><span class="nEVEventName"> <%# Eval("OwnerName") %></span> -->
    <!-- </div>
                        <div class="nTimeAndLocation nNearbyTimeAndLocation">
                            <div class="nExploreTime"><i class="fa fa-clock-o"></i>&nbsp <span class="nEVdate"><%# Eval("RemainedTime") %></span> </div>
                            <!--<div class="nExploreLocation">
                                <i class="fa fa-map-marker"></i>&nbsp<asp:Label ID="LabelLocation" runat="server" Text='<%# Eval("Location") %>' />
                            </div>-->
    <!-- </div>
                        <!-- <div class="nDots"><i class="fa fa-ellipsis-h"></i>&nbsp</div> -->
    <!-- <div class="clear"></div>
                        <span class="nEVBy">by</span>
                        <span class="nEVEventName"><%# Eval("OwnerName") %></span>
                        <div class="clear"></div>
                        <div class="nEventCoverBox">
                            <div class="nRoundPicture nActivityPicture">
                                <div class="invisible"><%# Eval("TypeId") %></div>
                            </div>
                        </div>
                        <div class="nEventCoverBox">
                            <div class="nRoundPicture nEVOwnerPicture">
                                <div class="invisible"><%# Eval("ProfilePicUrl") %></div>
                                <canvas class="nRequestCanvas" width="115" height="115"></canvas>
                            </div>
                        </div>
                        <div class="nEventCoverBox">
                            <div class="nRoundPicture nParticipantNumberPicture">
                                <div class="nParticipantNumberPictureTop">
                                    <%# Eval("ParticipantsAccepted") %> / <%# Eval("Participants") %>
                                    <canvas class="nFeedParticipantsCanvas" width="115" height="115"></canvas>
                                </div>
                                <div class="nParticipantNumberPictureBot">
                                </div>
                            </div>
                        </div>
                    <div class="nNearbyButton">SEND REQUEST</div>
                    </div>
                </div>

                <!-- each feed cover end -->
    <!-- <div class="invisible">
                    <asp:HiddenField ID="HiddenFieldCoverId" runat="server" Value='<%# Eval("CoverId") %>' />
                    <asp:HiddenField ID="HiddenFieldEventId" runat="server" Value='<%# Eval("EventId") %>' />
                    <asp:Label ID="LabelName" runat="server" Text='<%# Eval("Name") %>' />
                    <asp:Label ID="LabelRemainedTime" runat="server" Text='<%# Eval("RemainedTime") %>' />
                    <asp:HiddenField ID="HiddenFieldTypeId" runat="server" Value='<%# Eval("TypeId") %>' />
                    <asp:HiddenField ID="HiddenFieldUserId" runat="server" Value='<%# Eval("UserId") %>' />
                    <asp:HiddenField ID="HiddenFieldUserPhotoUrl" runat="server" Value='<%# Eval("ProfilePicUrl") %>' />
                    <asp:Label ID="LabelUserRate" runat="server" Text='<%# Eval("UserRate") %>' />
                    <asp:HiddenField ID="HiddenFieldParticipants" runat="server" Value='<%# Eval("Participants") %>' />
                </div>
                <br />
            </ItemTemplate>
        </asp:Repeater>

    </div>

    <!-- following-->
    <!-- <div class="nDescriptionContent nTabContents hidden">
                    <asp:Repeater ID="RepeaterFollowing" runat="server">
                        <ItemTemplate>
                            <div class="nContentCover nFeedCover">
                                <!-- <div class="nEachFeedTitleBar">
                                <div class="nMessagesPicture nEachFeedPicture"></div>
                                <div class="invisible"><%# Eval("OwnerName") %></div>
                                <div class="nEachFeedTime"><%# Eval("RemainedTime") %></div>
                            </div> -->
    <!--   <div class="invisible nFeedCoverId"><%# Eval("CoverId") %></div>
                                <div class="invisible nFeedEventId"><%# Eval("EventId") %></div>
                                <div class="invisible nFeedUserRate"><%# Eval("UserRate") %></div>
                                <div class="invisible nFeedParticipants"><%# Eval("Participants") %></div>
                                <div class="invisible nFeedParticipantsAvailable"><%# Eval("ParticipantsAccepted") %></div>
                                <div class="nContentCoverTransparent">
                                    <div class="nContentTitle">
                                        <b><%# Eval("Name") %>
                                        </b><span class="nEVBy">by</span><span class="nEVEventName"> <%# Eval("OwnerName") %></span>
                                    </div>
                                    <!-- <div class="nDots"><i class="fa fa-ellipsis-h"></i>&nbsp</div> -->

    <!--   <div class="clear"></div>
                                    <div class="nTimeAndLocation">
                                        <div class="nExploreTime"><i class="fa fa-clock-o"></i>&nbsp <span class="nEVdate"><%# Eval("RemainedTime") %></span> </div>
                                        <div class="nExploreLocation">
                                            <i class="fa fa-map-marker"></i>&nbsp<asp:Label ID="Label1" runat="server" Text='<%# Eval("Location") %>' />
                                        </div>
                                    </div>
                                    <div class="clear"></div>
                                    <div class="nEventCoverBox">
                                        <div class="nRoundPicture nActivityPicture">
                                            <div class="invisible"><%# Eval("TypeId") %></div>
                                        </div>
                                    </div>
                                    <div class="nEventCoverBox">
                                        <div class="nRoundPicture nEVOwnerPicture">
                                            <div class="invisible"><%# Eval("ProfilePicUrl") %></div>
                                            <canvas class="nRequestCanvas" width="115" height="115"></canvas>
                                        </div>
                                    </div>
                                    <div class="nEventCoverBox">
                                        <div class="nRoundPicture nParticipantNumberPicture">
                                            <div class="nParticipantNumberPictureTop">
                                                <%# Eval("ParticipantsAccepted") %> / <%# Eval("Participants") %>
                                                <canvas class="nFeedParticipantsCanvas" width="115" height="115"></canvas>
                                            </div>
                                            <div class="nParticipantNumberPictureBot">
                                                <b></b>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="invisible">
                                <asp:HiddenField ID="HiddenFieldEventId" runat="server" Value='<%# Eval("EventId") %>' />
                                <asp:Label ID="LabelName" runat="server" Text='<%# Eval("Name") %>' />
                                <asp:Label ID="LabeldRemainedTime" runat="server" Text='<%# Eval("RemainedTime") %>' />
                                <asp:HiddenField ID="HiddenFieldTypeId" runat="server" Value='<%# Eval("TypeId") %>' />
                                <asp:HiddenField ID="HiddenFieldCoverId" runat="server" Value='<%# Eval("CoverId") %>' />
                                <asp:HiddenField ID="HiddenFieldUserId" runat="server" Value='<%# Eval("UserId") %>' />
                                <asp:Label ID="LabelUserFullName" runat="server" Text='<%# Eval("UserFullName") %>' />
                                <asp:HiddenField ID="HiddenFieldUserPhotoUrl" runat="server" Value='<%# Eval("ProfilePicUrl") %>' />
                                <asp:Label ID="LabelLocation" runat="server" Text='<%# Eval("Location") %>' />
                                <asp:Label ID="LabelUserRate" runat="server" Text='<%# Eval("UserRate") %>' />
                                <asp:HiddenField ID="HiddenFieldParticipants" runat="server" Value='<%# Eval("Participants") %>' />
                            </div>
                        </ItemTemplate>
                    </asp:Repeater>
                </div>
            </div>
        </div>
        <asp:Repeater ID="RepeaterMap" runat="server">
            <ItemTemplate>
            </ItemTemplate>
        </asp:Repeater>
                                     -->






    <asp:HiddenField ID="HiddenFieldMode" runat="server" />
    <asp:HiddenField ID="HiddenFieldStatus" runat="server" />
    <asp:HiddenField ID="HiddenFieldTitle" runat="server" />
    <asp:HiddenField ID="HiddenFieldSmiley" runat="server" />
    <asp:HiddenField ID="HiddenFieldMessage" runat="server" />
    <asp:HiddenField ID="HiddenFieldLinksNumber" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink1Image" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink1Text" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink1Url" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink1Color" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink2Image" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink2Text" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink2Url" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink2Color" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink3Image" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink3Text" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink3Url" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink3Color" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink4Image" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink4Text" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink4Url" runat="server" />
    <asp:HiddenField ID="HiddenFieldLink4Color" runat="server" />
</asp:Content>
