<%@ Page Title="Notifications" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Notifications.aspx.cs" Inherits="WebApplication1.Notifications" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            generalLook();
            menu();
            notificationsPage();
        });
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle">Notifications</div>
    </div>
    <div class="nDoneSmiley invisible">:)</div>
    <div class="nDoneMessage invisible">There is no new notification.</div>
    <div class="nNotificationsAllContainer">
        <asp:Repeater ID="RepeaterNotifications" runat="server">
            <ItemTemplate>
                <div class="fullNotificationContainer">
                    <div class="nMessagesPicture nNotificationPicture nRequestsRequestPic">
                    </div>
                    <div class="nMessagesInsideDiv">
                        <div class="nNotificationBody">
                            <asp:Label ID="LabelText" runat="server" Text='<%# Eval("Text") %>'></asp:Label>
                        </div>
                        <div class="nNotificationX">
                            x
                        <div class="invisible"><%#Eval("NotificationId") %></div>
                        </div>
                        <div class="MessageListDate">
                            <div class="nSmallIcon nBlogClock nMessagesClock"></div>
                            <asp:Label ID="LabelDate" runat="server" Text='<%# Eval("PassedTime") %>'></asp:Label>
                        </div>
                    </div>
                    <div class="clear"></div>
                    <hr class="nMessagesHr nNotificationHr" />
                    <div class="invisible">
                        <asp:Label ID="LabelImage" CssClass="nNotificationImageUrl" runat="server" Text='<%# "Images/Icons/Notifications/"+ Eval("NotificationType") +"-24.png" %>'></asp:Label>
                        <asp:Label ID="LabelUnread" CssClass="nNotificationUnread" runat="server" Text='<%# Eval("Unread") %>'></asp:Label>
                        <asp:Button ID="ButtonDelete" runat="server" Text="" CommandName="Delete" CommandArgument='<%#Eval("NotificationId") %>' />
                        <div class="nNotificationLink">
                            <asp:HiddenField ID="HiddenFieldLink" runat="server" Value='<%#Eval("Link") %>' />
                        </div>
                    </div>
                </div>
            </ItemTemplate>
        </asp:Repeater>
    </div>
    <asp:HiddenField ID="HiddenFieldStatus" runat="server" />
</asp:Content>
