<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Profile.aspx.cs" Inherits="WebApplication1.Profile" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            profilePage();
            generalLook();
            menu();
        });
    </script>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle">Profile</div>
    </div>
    <div class="nContentCover nProfileCover">
        <div class="nContentCoverTransparent">
            <div class="nEventCoverBox ">
                <div class="arrow-right">
                    <div class="nVerified"></div>
                </div>
                <div class="nCountry">
                    <div class="nCountryFlag">
                    </div>
                    <div class="nProfileWhiteText">
                        <asp:Label ID="LabelCountry" runat="server"></asp:Label>
                    </div>
                    <div class="nProfileWhiteText">
                        <asp:Label ID="LabelCity" runat="server"></asp:Label>
                    </div>
                </div>

            </div>
            <div class="nEventCoverBox">
                <div class="nRoundPicture nProfpagePicture">
                    <canvas id="canvas2" width="115" height="115"></canvas>
                </div>
            </div>
            <div class="nEventCoverBox nFollowings">
                <div class="nProfileWhiteText nProfileFollowersLabel">
                    Followers
                </div>
                <div class="nProfileWhiteText nProfileFollowersLabel">
                    <asp:Label ID="LabelFollowers" runat="server" Text="# followers"></asp:Label>
                </div>
                <div class="nProfileWhiteText nProfileFollowingsLabel">
                    Following
                </div>
                <div class="nProfileWhiteText nProfileFollowingsLabel">
                    <asp:Label ID="LabelFollowing" runat="server" Text="# following"></asp:Label>
                </div>
            </div>
        </div>
    </div>


    <div class="clear"></div>
    <div class="nProfileMiddle">
        <div class="profileName nEVOwnerName">
            <b>
                <asp:Label ID="LabelName" runat="server"></asp:Label>
            </b>
        </div>
        <div class="profileName"><b>@<asp:Label ID="LabelUsername" runat="server"></asp:Label></b></div>
        <div class="nDots nDotsProfile">
            <i class="fa fa-ellipsis-h nDotsLogo"></i>
            <div class="clear"></div>
            <div class="nDotsBox nDotBoxLinks">
                <div class="nDotsBoxInsideContainer nDotsBoxInsideContainerLinks">
                    <!-- block user, not implemented yet -->
                    <!--<div class="nDotsBoxEachLogo nDotsBoxEachLogoBlock"></div>
                    <div class="nDotsBoxEach">Block user</div>
                    -->

                    <div class="nDotsBoxEachLogo nDotsBoxEachLogoReport"></div>
                    <div class="nDotsBoxEach">Report user</div>
                </div>
                <div class="nDotsBoxInsideContainer nDotsBoxInsideContainerEdit invisible">
                    <div class="nDotsBoxEachLogo nDotsEditProfile"></div>
                    <div class="nDotsBoxEach">Edit profile</div>
                </div>
            </div>
        </div>
        <div class="nProfileUserDescription">
            <asp:Label ID="LabelAbout" runat="server"></asp:Label>
        </div>
        <div class="nProfileFollowButton">FOLLOW</div>
    </div>

    <div class="nProfileTabbedContent">
        <div class="nTabsHolder">
            <div class="nTabs nTabs4 nExploreSelected" ntabnumber="1">
                <b>EVENTS</b>
            </div>
            <div class="nTabs nTabs4 reviewButton" ntabnumber="2">
                <b>REVIEW</b>
            </div>
            <div class="nTabs nTabs4" ntabnumber="3">
                <b>FOLLOWERS</b>
            </div>
            <div class="nTabs nTabs4" ntabnumber="4">
                <b>FOLLOWING</b>
            </div>
        </div>
        <div class="nExploreContentHolder nProfileContentHolder">
            <!-- events-->
            <div class="nDescriptionContent nTabContents">
                <div class="nDoneSmiley nDoneSmileyNoEvents invisible">:)</div>
                <div class="nDoneMessage nDoneMessageNoEvents invisible">The user hasn't created any events yet.</div>
                <div class="nProfileEventsOuterContainer">
                    <asp:Repeater ID="RepeaterEvents" runat="server">
                        <ItemTemplate>
                            <div class="fullNotificationContainer nEventsNotificationContiner">
                                <div class="nMessagesPicture nEventsPicture">
                                    <asp:HiddenField ID="HiddenFieldTypeId" runat="server" Value='<%# Eval("TypeId") %>' />
                                </div>
                                <div class="nMessagesInsideDiv">
                                    <div class="MessageSender">
                                        <asp:HyperLink ID="HyperLinkEvent" runat="server" CssClass="nEventsUrl" NavigateUrl='<%# "~/Events/"+ Eval("EventId") %>'><%# Eval("Name") %></asp:HyperLink>
                                    </div>
                                    <div class="MessageBody">
                                    </div>
                                    <div class="clear"></div>
                                    <div class="MessageListDate">
                                        <div class="nSmallIcon nBlogClock nMessagesClock">
                                        </div>
                                        <asp:Label ID="LabelDate" runat="server" Text='<%# Eval("RemainedTime") %>'></asp:Label>
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <hr class="nMessagesHr" />
                            </div>
                        </ItemTemplate>
                    </asp:Repeater>
                </div>
                <asp:HiddenField ID="HiddenFieldEventsStatus" runat="server" />
                <div class="nProfileErrorMessage">
                </div>
            </div>

            <!-- reviews-->
            <div class="nBoardContent nTabContents hidden">
                <div class="nDoneSmiley nDoneSmileyNoReviews invisible">:)</div>
                <div class="nDoneMessage nDoneMessageNoReviews invisible">The user is not reviewed by anyone yet.</div>
                <div class="nProfileReviewsOuterContainer">
                    <div class="nGraphTitle">
                        <div class="nGraphTitleNumber">
                            <asp:Label ID="LabelRatePercent" runat="server" Text="0"></asp:Label>%  
                        </div>
                        <div class="nGraphTitleRating">
                            <asp:Label ID="LabelRateCount" runat="server" Text="0"></asp:Label>
                            <span class='nProfileRatingsWord'>rating</span>
                        </div>
                    </div>
                    <div class="nBarGraphs">
                        <div>
                            <div class="nLeft nBarGraphsNumbers nGraphBarNumber1">:D</div>
                            <div class="nBarGraphRight nBarGraphRight1">
                                <div class="nGraphBar animationAll nGraphBar1" data-score="0">
                                    <asp:Label ID="LabelRateFive" CssClass="invisible" runat="server" Text="0"></asp:Label>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div>
                            <div class="nLeft nBarGraphsNumbers nGraphBarNumber2">:)</div>
                            <div class="nBarGraphRight nBarGraphRight2">
                                <div class="nGraphBar nGraphBar2 animationAll" data-score="0">
                                    <asp:Label ID="LabelRateFour" CssClass="invisible" runat="server" Text="0"></asp:Label>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div>
                            <div class="nLeft nBarGraphsNumbers nGraphBarNumber3">:|</div>
                            <div class="nBarGraphRight nBarGraphRight3">
                                <div class="nGraphBar nGraphBar3 animationAll" data-score="0">
                                    <asp:Label ID="LabelRateThree" CssClass="invisible" runat="server" Text="0"></asp:Label>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div>
                            <div class="nLeft nBarGraphsNumbers nGraphBarNumber4">:(</div>
                            <div class="nBarGraphRight nBarGraphRight4">
                                <div class="nGraphBar nGraphBar4 animationAll" data-score="0">
                                    <asp:Label ID="LabelRateTwo" CssClass="invisible" runat="server" Text="0"></asp:Label>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div>
                            <div class="nLeft nBarGraphsNumbers nGraphBarNumber5">:((</div>
                            <div class="nBarGraphRight nBarGraphRight5">
                                <div class="nGraphBar nGraphBar5" data-score="0">
                                    <asp:Label ID="LabelRateOne" CssClass="invisible" runat="server" Text="0"></asp:Label>
                                </div>
                            </div>
                            <div class="clear"></div>
                        </div>
                    </div>

                    <div class="clear"></div>
                    <div>
                        <asp:Repeater ID="RepeaterReviews" runat="server">
                            <ItemTemplate>
                                <div class="nProfileEachReview">
                                    <div class="nMessagesPicture nEVMessagesPicture nProfileReviewPicture">
                                        <asp:HiddenField ID="HiddenFieldProfilePicUrl" runat="server" Value='<%# Eval("ProfilePicUrl") %>' />
                                        <div class="nFBEachOuterContainer nProfileEachOuterContainer" data-value="2">
                                            <div class="nFBEachContainer ">
                                                <div class="nFBEachLogo">
                                                    :(
                                                <div class="invisible">
                                                    <asp:Label ID="LabelRate" runat="server" CssClass="nProfileReviewHeartText" Text='<%# Eval("Rate") %>'></asp:Label>
                                                </div>
                                                </div>
                                            </div>
                                            <!--<div class="nFBEachText">bad</div>-->
                                        </div>
                                        <!-- <div class="nSmallIcon nDotsBoxEachLogoBookmark nProfileMessagesHeart"></div>-->
                                    </div>
                                    <div class="invisible">
                                    </div>
                                    <div class="nProfileMessageSender">
                                        <asp:HyperLink ID="HyperLinkReviewer" runat="server" NavigateUrl='<%#"~/Profile/"+ Eval("UserId") %>' CssClass="nProfileReviewerName"><%#Eval("FirstName") + " " + Eval("LastName") %></asp:HyperLink>
                                    </div>
                                    <br />
                                    <div class="nProfileReviewBody">
                                        <asp:Label ID="LabelComment" runat="server" Text='<%# Eval("Comment") %>'></asp:Label>
                                    </div>
                                    <div class="clear"></div>
                                    <div class="MessageListDate nProfileReviewDate">
                                        <div class="nSmallIcon nBlogClock nMessagesClock"></div>
                                        <asp:Label ID="LabelSubmitDate" runat="server" Text='<%# Eval("SubmitDate") %>'></asp:Label>
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <hr class="nMessagesHr nMessagesProfileReviewHr">
                            </ItemTemplate>
                        </asp:Repeater>
                        <asp:HiddenField ID="HiddenFieldReviewsStatus" runat="server" />
                    </div>
                    <div class="nProfileErrorMessage">
                    </div>
                </div>
            </div>

            <!-- followers-->
            <div class="nParticipantsContent nTabContents hidden">
                <div class="nDoneSmiley nDoneSmileyNoFollowers invisible">:)</div>
                <div class="nDoneMessage nDoneSmileyNoFollowers invisible">The user is not followed by anyone yet.</div>
                <div class='nProfileFollowersOuterContainer'>
                    <asp:Repeater ID="RepeaterFollowers" runat="server">
                        <ItemTemplate>
                            <div class="nProfileFollowersContainer">
                                <div class="nMessagesPicture nEVMessagesPicture nProfileFollowersPicture">
                                    <asp:HiddenField ID="HiddenFieldProfilePicUrl" runat="server" Value='<%# Eval("ProfilePicUrl") %>' />
                                </div>
                                <asp:HyperLink ID="HyperLinkParticipant" runat="server" NavigateUrl='<%#"~/Profile/"+ Eval("UserId") %>' CssClass="nEVparticipantName nNoDecoration"><%#Eval("FirstName") + " " + Eval("LastName") %></asp:HyperLink>
                                <div class="clear"></div>
                            </div>
                            <br />
                        </ItemTemplate>
                    </asp:Repeater>
                </div>
                <asp:HiddenField ID="HiddenFieldFollowersStatus" runat="server" />
                <div class="nProfileErrorMessage">
                    <asp:Label ID="LabelFollowersNoRecord" runat="server" Visible="True"></asp:Label>
                </div>
            </div>

            <!-- followings-->
            <div class="nMapContent nTabContents hidden">
                <div class="nDoneSmiley nDoneSmileyNoFollowings invisible">:)</div>
                <div class="nDoneMessage nDoneSmileyNoFollowings invisible">The user does not follow anyone yet.</div>
                <div class="nProfileFollowingsOuterContainer">
                    <asp:Repeater ID="RepeaterFollowing" runat="server">
                        <ItemTemplate>
                            <div class="nProfileFollowingsContainer">
                                <div class="nMessagesPicture nEVMessagesPicture nProfileFolloweingPicture">
                                    <asp:HiddenField ID="HiddenFieldProfilePicUrl" runat="server" Value='<%# Eval("ProfilePicUrl") %>' />
                                </div>
                                <asp:HyperLink ID="HyperLinkParticipant" runat="server" NavigateUrl='<%#"~/Profile/"+ Eval("UserId") %>' CssClass="nEVparticipantName nNoDecoration"><%#Eval("FirstName") + " " + Eval("LastName") %></asp:HyperLink>
                                <div class="clear"></div>
                                <br />
                            </div>
                        </ItemTemplate>
                    </asp:Repeater>

                    <asp:HiddenField ID="HiddenFieldFollowingStatus" runat="server" />
                    <div class="nProfileErrorMessage">
                        <asp:Label ID="LabelFollowingNoRecord" runat="server" Visible="True"></asp:Label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="nExploreFooter nThickFooter">
        <!--<div class="nFooterButton nProfileMessageButton">WRITE A MESSAGE</div> -->
        <div class="nFooterButton nNotButton invisible"><div class="nFooter1Image nProfileImageOrage"></div><span>REGISTER</span></div>
        <div class="nFooterButton nRequestButton invisible"><div class="nFooter1Image nProfileImageGreen"></div><span>LOGIN</span></div>
        <div class="nFooterButton nProfileMessageButton invisible"><div class="nFooter1Image nProfileImageGrey"></div><span>SEND MESSAGE</span></div>
    </div>

    <div class="invisible">
        <!-- profile rate -->
        <asp:Label ID="LabelRate" runat="server"></asp:Label>
        <asp:Button ID="ButtonFollow" runat="server" Text="Button" OnClick="ButtonFollow_Click" />
    </div>
    <asp:HiddenField ID="HiddenFieldUserId" runat="server" />
    <asp:HiddenField ID="HiddenFieldCoverUrl" runat="server" />
    <asp:HiddenField ID="HiddenFieldProfilePhoto" runat="server" />


    <asp:HiddenField ID="HiddenFieldFollowText" runat="server" />
    <asp:HiddenField ID="HiddenFieldFlagId" runat="server" />
    <asp:HiddenField ID="HiddenFieldProfileVerified" runat="server" />
    <asp:HiddenField ID="HiddenFieldButtonStatus" runat="server" />

    <asp:HiddenField ID="HiddenFieldToastStatus" runat="server" Value="0" />
    <asp:HiddenField ID="HiddenFieldToastMode" runat="server" />
    <asp:HiddenField ID="HiddenFieldToastSmiley" runat="server" />
    <asp:HiddenField ID="HiddenFieldToastMessage" runat="server" />
    <asp:HiddenField ID="HiddenFieldButton1Text" runat="server" />
    <asp:HiddenField ID="HiddenFieldButton2Text" runat="server" />
    <asp:HiddenField ID="HiddenFieldButton1Color" runat="server" />
    <asp:HiddenField ID="HiddenFieldButton2Color" runat="server" />
    <asp:HiddenField ID="HiddenFieldButton1Url" runat="server" />
    <asp:HiddenField ID="HiddenFieldButton2Url" runat="server" />
    <!--
        <asp:Label ID="LabelMessage" runat="server" Visible="False"></asp:Label>
        <asp:HyperLink ID="HyperLinkEdit" runat="server" Visible="False" NavigateUrl="~/Settings">Edit Profile</asp:HyperLink>
        -->
</asp:Content>
