<%@ Page Title="Report" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Report.aspx.cs" Inherits="WebApplication1.Report" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            reportPage();
            generalLook();
            menu();
        });
    </script>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle">Report</div>
    </div>
    <br />
    <div class="nEAContentHolder">
        <asp:Label ID="Label1" AssociatedControlID="DropDownListReportType" runat="server" Text="You want to report:"></asp:Label>
        <asp:Label ID="LabelReportItem" runat="server"></asp:Label>
        <asp:DropDownList ID="DropDownListReportType" runat="server" data-role="none" CssClass="nCompletionTextInput "></asp:DropDownList>
        <br />
        <br />
        <asp:Label ID="Label2" AssociatedControlID="TextBoxMessage" runat="server" Text="Write a message:" ></asp:Label>
        <asp:TextBox ID="TextBoxMessage" runat="server" TextMode="multiline" data-role="none"  CssClass="nCompletionTextInput "></asp:TextBox>
        <!-- <asp:Label ID="Label3" AssociatedControlId="TextBoxPage" runat="server" Text="Provide the page name please:"></asp:Label>
        <asp:TextBox ID="TextBoxPage"  runat="server"></asp:TextBox>
            -->
        <div class="invisible">
            <asp:Button ID="ButtonSubmit" runat="server" Text="Button" OnClick="ButtonSubmit_Click" />
        </div>
        <asp:HiddenField ID="HiddenFieldErrorMode" runat="server" Value="0" />
    </div>
    <div class="nExploreFooter nThickFooter">
        <div class="nFooterButton nProfileMessageButton nRequestButton"><div class="nFooter1Image nProfileImageGreen"></div>SEND REPORT</div>
    </div>
</asp:Content>
