<%@ Page Title="Requests" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="RequestsShow.aspx.cs" Inherits="WebApplication1.RequestsShow" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            requestsShowPage();
            generalLook();
            menu();
        });
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle">Requests</div>
    </div>


    <asp:Repeater ID="RepeaterRequests" runat="server">
        <%-- 
                        Requests/{RequestId}/{ActionCode}
                        action code 1 for accept
                        action code 2 for reject
        --%>
        <ItemTemplate>
            <div class="fullNotificationContainer">
                <div class="nMessagesPicture nNotificationPicture">
                </div>
                <div class="nMessagesInsideDiv">
                    <div class="nRequestshowName">
                        <asp:HyperLink ID="HyperLinkName" runat="server" NavigateUrl='<%# "~/Profile/"+ Eval("SenderId") %>'><%# Eval("FullName") %></asp:HyperLink>
                    </div>
                    <div class="nNotificationBody">
                        <%# Eval("Message") %>
                        <p></p>
                    </div>
                    <div class="MessageListDate">
                        <div class="nSmallIcon nBlogClock nMessagesClock"></div>
                        <%# Eval("PassedTime") %>
                    </div>
                    <div class="nRequestShowActionContainer">
                        <div class="nRequestShowActionOk">
                        </div>
                        <div class="nRequestShowActionNot">
                        </div>
                        <div class="nRequestShowRequestId invisible"><%# Eval("RequestId") %></div>
                        <div class="nRequestShowEventId invisible"><%# Eval("EventId") %></div>
                    </div>
                </div>
                <div class="clear"></div>
                <hr class="nMessagesHr nNotificationHr" />
                <div class="invisible">
                    <asp:Label ID="LabelPassedTime" runat="server" Text='<%# Eval("PassedTime") %>' />

                    <asp:Label ID="LabelProfilePicUrl" CssClass="nNotificationImageUrl" runat="server" Text='<%# Eval("ProfilePicUrl") %>'></asp:Label>
                    <asp:Label ID="LabelMessage" runat="server" Text='<%# Eval("Message") %>'></asp:Label>
                    <asp:Label ID="LabelRequestId" runat="server" Text='<%# Eval("RequestId") %>' />
                </div>
            </div>
        </ItemTemplate>
    </asp:Repeater>
</asp:Content>
