<%@ Page Title="Review" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Review.aspx.cs" Inherits="WebApplication1.Review" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>

        $(document).ready(function () {
            ReviewPage();
            generalLook();
            menu();
        });
    </script>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle" id="demo">Review</div>
    </div>
    <div class="pageErrorContent invisible">
        <div class="nDoneSmiley">:)</div>
        <div class="nDoneMessage">Message</div>
        <div class="nDoneAllButtons">
            <div class="nDoneButton nDoneButton4 invisible">
                <div class="nDoneImage nDoneImage4"></div>
                <div class="nDoneInsideImage nDoneInsideImage4"></div>
                <div class="nDoneText nDoneText4">4</div>
            </div>
            <div class="nDoneButton nDoneButton3 invisible">
                <div class="nDoneImage nDoneImage3"></div>
                <div class="nDoneInsideImage nDoneInsideImage3"></div>
                <div class="nDoneText nDoneText3">3</div>
            </div>
            <div class="nDoneButton nDoneButton2 invisible">
                <div class="nDoneImage nDoneImage2"></div>
                <div class="nDoneInsideImage nDoneInsideImage2"></div>
                <div class="nDoneText nDoneText2">2</div>
            </div>
            <div class="nDoneButton nDoneButton1 invisible">
                <div class="nDoneImage nDoneImage1"></div>
                <div class="nDoneInsideImage nDoneInsideImage1"></div>
                <div class="nDoneText nDoneText1">1</div>
            </div>
        </div>
    </div>
    <div class="pageNormalContent invisible">
        <div class="nContentCover nReviewCover">
            <div class="nContentCoverTransparent">
                <div class="nContentTitle">
                    <b>Unknown
                    </b>
                </div>
                <div class="clear"></div>
                <div class="nEventCoverBox ">
                </div>
                <div class="nEventCoverBox">
                    <div class="nRoundPicture nProfpagePicture">
                    </div>
                </div>
                <div class="nEventCoverBox nFollowings">
                </div>
            </div>
        </div>



        <br />
        <div class="nReviewRevieweePhoto nRoundPicture "></div>
        <br />
        <div class="nDoneMessage nDoneMessageCompact">
            <asp:Label ID="Label2" runat="server" Text="Recently you went to "></asp:Label>
            <asp:Label ID="LabelEventName" runat="server"></asp:Label>
            <span class="nReviewEventNameLabel"></span>
            <span>with</span>
            <!-- <asp:HyperLink ID="HyperLinkUser" runat="server" CssClass="nReviewUserLink">[HyperLinkUser]</asp:HyperLink> -->
            <a class="nReviewUserLink"></a>
            <span>.</span>
            <asp:Label ID="Label3" runat="server" Text="Please review your experience."></asp:Label>
        </div>
        <br />
        <div class="nFBEachOuterContainer " data-value="1">
            <div class="nFBEachContainer">
                <div class="nFBEachLogo">:((</div>
            </div>
            <div class="nFBEachText">awful</div>
        </div>
        <div class="nFBEachOuterContainer" data-value="2">
            <div class="nFBEachContainer">
                <div class="nFBEachLogo">:(</div>
            </div>
            <div class="nFBEachText">bad</div>
        </div>
        <div class="nFBEachOuterContainer" data-value="3">
            <div class="nFBEachContainer">
                <div class="nFBEachLogo">:|</div>
            </div>
            <div class="nFBEachText">so-so</div>
        </div>
        <div class="nFBEachOuterContainer" data-value="4">
            <div class="nFBEachContainer">
                <div class="nFBEachLogo">:)</div>
            </div>
            <div class="nFBEachText">good</div>
        </div>
        <div class="nFBEachOuterContainer nFBEachOuterContainerSelected" data-value="5">
            <div class="nFBEachContainer">
                <div class="nFBEachLogo">:D</div>
            </div>
            <div class="nFBEachText">awsome</div>
        </div>
        <div class="clear"></div>
        <div class="nDoneMessage">
            <asp:Label ID="Label4" runat="server" Text="Any comments to add?"></asp:Label>
        </div>
        <br />
        <div class="nEAContentHolder">
            <asp:TextBox ID="TextBoxComment" CssClass="nReveiwCommentBox" runat="server" MaxLength="200"></asp:TextBox>
        </div>
        <br />
        <div class="nExploreFooter nThickFooter">
            <div class="nFooterButton nNotButton"><div class="nFooter1Image nProfileImageOrange"></div><span>NOT NOW</span></div>
            <div class="nFooterButton nRequestButton"><div class="nFooter1Image nProfileImageGreen"></div><span>SEND THE REVIEW</span></div>
        </div>
        <asp:HiddenField ID="HiddenFieldRate" runat="server" Value="5" />
        <asp:HiddenField ID="HiddenFieldUserPhotoUrl" runat="server" />
        <asp:HiddenField ID="HiddenFieldTypeId" runat="server" />
        <asp:HiddenField ID="HiddenFieldCoverId" runat="server" />
        <asp:HiddenField ID="HiddenFieldReviewRequestId" runat="server" />
        <div class="invisible">
            <!-- <asp:Button ID="ButtonSubmit" runat="server" OnClick="ButtonSubmit_Click" Text="Submit" />
            <asp:Button ID="ButtonCancel" runat="server" Text="Button" OnClick="ButtonCancel_Click" /> -->
        </div>
        <!--<asp:Label ID="Label1" runat="server" Text="Hi!"></asp:Label>-->
        <asp:HiddenField ID="HiddenFieldStatus" runat="server" />
        <asp:HiddenField ID="HiddenFieldTitle" runat="server" />
        <asp:HiddenField ID="HiddenFieldSmiley" runat="server" />
        <asp:HiddenField ID="HiddenFieldMessage" runat="server" />
        <asp:HiddenField ID="HiddenFieldLinksNumber" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink1Image" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink1Text" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink1Url" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink1Color" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink2Image" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink2Text" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink2Url" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink2Color" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink3Image" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink3Text" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink3Url" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink3Color" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink4Image" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink4Text" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink4Url" runat="server" />
        <asp:HiddenField ID="HiddenFieldLink4Color" runat="server" />
    </div>
</asp:Content>
