<%@ Page Title="Search" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Search.aspx.cs" Inherits="WebApplication1.Search" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Login</title>
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            generalLook();
            menu();
            messagesPage();
            searchPage();
        });
    </script>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton ">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle">Search</div>
    </div>

    <div class="nTabbedContent ">
        <div class="nTabsHolder">
            <div class="nTabs nExploreSelected nTabs3" ntabnumber="1">
                <b>TAG</b>
            </div>
            <div class="nTabs reviewButton nTabs3" ntabnumber="2">
                <b>TYPE</b>
            </div>
            <div class="nTabs nTabs3" ntabnumber="3">
                <b>PEOPLE</b>
            </div>
        </div>
        <div class="nExploreContentHolder nProfileContentHolder">
            <!-- tag -->
            <div class="nDescriptionContent nTabContents">
                <div class="nSmallIcon nMarkerIcon"></div>
                <div class="nSearchLocation">
                    <span class="nSearchLocationSpan">NA </span><span class="nSearchChange">&nbsp;(Change)</span>
                </div>
                <!-- <div class="nRight nSearchLocationLink"><a href="#">Change Location</a></div> -->
                <div class="clear"></div>
                <div class="nMessageSendArea nSearchMessageSendArea">
                    <div class="nMSSendButton nSearchButton nSearchTagButton">
                    </div>
                    <div class="nMSTextArea nSearchTextArea">
                        <asp:TextBox ID="TextBoxTag" runat="server" data-mini="true" CssClass="TextBoxMultiR2L nSearchTagInput" placeholder="Tag" data-autogrow="false" data-role="none"></asp:TextBox>
                    </div>
                    <div class="nSearchResultsTag">
                    </div>
                </div>
                <!-- <div class="nLeft nSearchSearchBox">
                    
                </div>
                <div class="nRight nSearchButton nSearchTagButton"></div>
                    -->
            </div>
            <!-- filter -->
            <div class="nBoardContent nTabContents hidden">
                <div class="nSmallIcon nMarkerIcon"></div>
                <div class="nSearchLocation">
                    <span class="nSearchLocationSpan">NA </span><span class="nSearchChange">&nbsp;(Change)</span>
                </div>
                <!-- <div class="nRight nSearchLocationLink"><a href="#">change location</a></div> -->
                <div class="clear"></div>
                <div class="nSearchLogos">
                    <div class="nSearchLogoContainer">
                        <div class="nSearchLogo nActivityTheater" data="Art / culture" activity-id="1"></div>
                    </div>
                    <div class="nSearchLogoContainer">
                        <div class="nSearchLogo nActivityBook" data="Education" activity-id="2"></div>
                    </div>
                    <div class="nSearchLogoContainer">
                        <div class="nSearchLogo nActivityDance" data="Entertainment" activity-id="3"></div>
                    </div>
                    <div class="nSearchLogoContainer">
                        <div class="nSearchLogo nActivityRestaurant" data="Food/drink" activity-id="4"></div>
                    </div>
                    <div class="nSearchLogoContainer">
                        <div class="nSearchLogo nActivityNature" data="Outdoor" activity-id="5"></div>
                    </div>
                    <div class="nSearchLogoContainer">
                        <div class="nSearchLogo nActivityShopping" data="Shopping" activity-id="6"></div>
                    </div>
                    <div class="nSearchLogoContainer">
                        <div class="nSearchLogo nActivitySport" data="Sports" activity-id="7"></div>
                    </div>
                    <div class="nSearchLogoContainer">
                        <div class="nSearchLogo nActivityMore" data="Others" activity-id="8"></div>
                    </div>
                </div>
                <div class="nMiddle nSearchButton nSearchFilterButton"></div>
                <div class="clear"></div>
                <div class="nSearchResultsFilter">
                </div>
            </div>
            <!-- people -->
            <div class="nParticipantsContent nTabContents hidden">
                <div class="nMessageSendArea">
                    <div class="nMSSendButton nSearchButton nSearchPeopleButton">
                        <b></b>
                    </div>
                    <div class="nMSTextArea nSearchPeopleTextArea">
                        <asp:TextBox ID="TextBoxUsername" runat="server" CssClass="TextBoxMultiR2L nSearchPeopleInput" data-autogrow="false" data-role="none" placeholder="Username"></asp:TextBox>
                    </div>
                    <div class="nSearchResultsPeople">
                    </div>
                </div>

                <!-- <div class="nLeft nSearchSearchBox">
                </div>
                <div class="nRight nSearchButton nSearchTagButton"></div> -->
            </div>
            <div class="nSearchResults invisible">
                <asp:Label ID="LabelMessage" runat="server" Text="Label" Visible="False"></asp:Label>
                <asp:Panel ID="PanelResult" runat="server" Visible="False">
                    <asp:Repeater ID="RepeaterResult" runat="server">
                        <ItemTemplate>
                            <div class="fullNotificationContainer nEventsNotificationContiner">
                                <div class="nMessagesPicture nEventsPicture">
                                </div>
                                <div class="nMessagesInsideDiv">
                                    <div class="MessageSender">
                                        <a href="#">
                                            <asp:Label ID="Label2" runat="server" Text='<%# Eval("Name") %>'></asp:Label></a>
                                    </div>
                                    <div class="MessageBody">
                                    </div>
                                    <div class="clear"></div>
                                    <div class="MessageListDate">
                                        <div class="nSmallIcon nBlogClock nMessagesClock">
                                        </div>
                                        <asp:Label ID="Label3" runat="server" Text='<%# Eval("RemainedDate") %>'></asp:Label>
                                    </div>
                                    <div class="invisible">
                                        <asp:Label ID="LabelTypeId" runat="server" CssClass="nSREventTypeId" Text='<%# Eval("TypeId") %>'></asp:Label>
                                        <asp:Label ID="LabelImage0" runat="server" CssClass="nSREventId" Text='<%# Eval("EventId") %>'></asp:Label>
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <hr class="nMessagesHr" />
                                <div class="invisible">

                                    <asp:Label ID="Label4" runat="server" Text='<%# Eval("ParticipantsRemained") %>'></asp:Label>
                                </div>
                            </div>
                        </ItemTemplate>
                    </asp:Repeater>
                </asp:Panel>
                <asp:Panel ID="PanelUsername" runat="server" Visible="False">
                    <asp:Repeater ID="RepeaterUsername" runat="server">
                        <ItemTemplate>
                            <div class="nProfileFollowingsContainer">
                                <div class="nMessagesPicture nEVMessagesPicture nProfileFolloweingPicture">
                                </div>
                                <div class="clear"></div>
                                <br />
                                <asp:HyperLink ID="HyperLink1" runat="server" CssClass="nEVparticipantName nNoDecoration nSRPeopleName" NavigateUrl='<%# "~/Profile/"+ Eval("UserId") %>'><%# Eval("Username") %></asp:HyperLink>
                                <div class="invisible">
                                    <asp:Label ID="LabelImage" runat="server" Text='<%# Eval("ProfilePicUrl") %>'></asp:Label>
                                    <div class="nSRPeopleId"><%# Eval("UserId") %></div>
                                </div>
                            </div>

                        </ItemTemplate>
                    </asp:Repeater>
                </asp:Panel>
            </div>
            <div class="hidden">
                <asp:Button ID="ButtonSearch" runat="server" Text="Search" OnClick="ButtonSearch_Click" />
            </div>
        </div>
    </div>
    <div class="invisible">
        <asp:Label ID="LabelLocation" runat="server" Text="Label"></asp:Label>
    </div>
    <div class="nSearchErrorContainer invisible">
        <div class="nDoneSmiley nDoneSmileyNoEvents ">:)</div>
        <div class="nDoneMessage nDoneMessageNoEvents ">No results found.</div>
    </div>
    <asp:HiddenField ID="HiddenFieldTypeId" runat="server" Value="1" />
    <asp:HiddenField ID="HiddenFieldSearchType" runat="server" Value="3" />
    <asp:HiddenField ID="HiddenFieldSearchStatus" runat="server" />
    <asp:HiddenField ID="HiddenFieldTagStatus" runat="server" />
</asp:Content>
