<%@ Page Title="Settings" Language="C#" MasterPageFile="~/MasterPageUser.Master" AutoEventWireup="true" CodeBehind="Settings.aspx.cs" Inherits="WebApplication1.Settings" EnableEventValidation="false" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link rel="stylesheet" href="../../../Styles/themes/moody.min.css" />
    <link rel="stylesheet" href="../../../Styles/themes/jquery.mobile.icons.min.css" />
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.3/jquery.mobile.structure-1.4.3.min.css" />
    <link rel="stylesheet" href="../../../Styles/font-awesome-4.2.0/css/font-awesome.min.css" />
    <link href="Images/favicon.png" rel="icon" type="image/png" />

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script>
        $(document).on("mobileinit", function () {
            $.mobile.selectmenu.prototype.options.nativeMenu = false;
        });
        $(document).bind("mobileinit", function () {
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script src="../../../JS/script.js"></script>
    <script src="../../../JS/jquery-ui.min.js"></script>
    <script src="../../../JS/jquery.cookie.js"></script>

    <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
    <link rel="stylesheet" href="../../../Styles/style.css" />
    <link rel="stylesheet" href="../../../Styles/jquery-ui.min.css" />

    <!-- signalR -->
    <!--Reference the SignalR library. -->
    <script src="../../../Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="../../../signalr/hubs"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script>
        $(document).ready(function () {
            settingsPage();
            generalLook();
            menu();
        });
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="nHeader">
        <div class="nMenuButton">
            <div class="nMenuButtonLogo">
            </div>
            <div class="nMenuNotification nMenuButtonNotification">
                <figure class="front">0</figure>
                <figure class="back">0</figure>
            </div>
        </div>
        <div class="nMenuAdd"></div>
        <div class="nPageTitle">Settings</div>
    </div>
    <!-- header end -->

    <asp:Panel ID="PanelMenu" runat="server" Visible="True">
        <script>
            $(document).ready(function () {
                $('.nMainPanelDiv').addClass('nfullHeight');
            });
        </script>
        <div>
            <div class="nSettingsList nSettingsListInformation">
                <div class="nSettingsListText"><b>Information</b></div>
                <div class="nSettingsListArrow"></div>
                <div class="clear"></div>
            </div>
            <hr class="nSettingsHr" />
            <div class="nSettingsList nSettingsListPhoto">
                <div class="nSettingsListText"><b>Photo and Cover</b></div>
                <div class="nSettingsListArrow"></div>
                <div class="clear"></div>
            </div>
            <hr class="nSettingsHr" />
            <div class="nSettingsList nSettingsListLocation">
                <div class="nSettingsListText"><b>Location</b></div>
                <div class="nSettingsListArrow"></div>
                <div class="clear"></div>
            </div>
            <hr class="nSettingsHr" />
            <div class="nSettingsList nSettingsListPreferences">
                <div class="nSettingsListText"><b>Preferences</b></div>
                <div class="nSettingsListArrow"></div>
                <div class="clear"></div>
            </div>
            <hr class="nSettingsHr" />
            <div class="nSettingsList nSettingsListAccount">
                <div class="nSettingsListText"><b>Account</b></div>
                <div class="nSettingsListArrow"></div>
                <div class="clear"></div>
            </div>
            <hr class="nSettingsHr" />
            <!-- <div class="nSettingsList nSettingsListPrivacy">
                <div class="nSettingsListText"><b>Privacy</b></div>
                <div class="nSettingsListArrow"></div>
                <div class="clear"></div>
            </div>
            <hr class="nSettingsHr" />
                -->
        </div>
    </asp:Panel>


    <!-- edit information settings -->
    <asp:Panel ID="PanelInformation" runat="server" Visible="False">
        <script>
            $('.nPageTitle').html("Settings - Information");
        </script>

        <div class="nSIRow">
            <div class="nSIview">
                <div class="nSIRowTitle">First Name</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue invisible  nSIRowFirstName">Unknown</div>
            </div>
            <div class="nSImodify nSImodifyFirstName invisible">
                <div class="nSIRowTitle">
                    <br />
                    <asp:TextBox ID="TextBoxFirstName" runat="server" data-role="none" CssClass="nTextInput"></asp:TextBox>
                    <br />
                    <br />
                </div>
                <div class="nSIHelper nSIHelperFirstName">
                    <div class="nSIRowEnterArrow"></div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="nSettingsValidationErrorMessage nSettingsFNError invisible">Please enter a valid first name</div>
        <hr class="nSettingsHr" />
        <div class="nSIRow">
            <div class="nSIview">
                <div class="nSIRowTitle">Last name</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue nSIRowLastName">Unknown</div>
            </div>
            <div class="nSImodify invisible nSImodifyLastName">
                <div class="nSIRowTitle">
                    <br />
                    <asp:TextBox ID="TextBoxLastName" runat="server" data-role="none" CssClass="nTextInput"></asp:TextBox>
                    <br />
                    <br />
                </div>
                <div class="nSIHelper nSIHelperLastName">
                    <div class="nSIRowEnterArrow"></div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="nSettingsValidationErrorMessage nSettingsLNError invisible">Please enter a valid last name</div>
        <hr class="nSettingsHr" />
        <div class="nSIRow">
            <div class="nSIview ">
                <div class="nSIRowTitle">Username</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue nSIRowUserName">Please enter</div>
            </div>
            <div class="nSImodify invisible nSImodifyUserName">
                <div class="nSIRowTitle">
                    <br />
                    <asp:TextBox ID="TextBoxUsername" runat="server" data-role="none" CssClass="nTextInput"></asp:TextBox>
                    <br />
                    <br />
                </div>
                <div class="nSIHelper nSIHelperUsername">
                    <div class="nSIRowEnterArrow"></div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="nSettingsValidationErrorMessage nSettingsUNError invisible">Please enter a valid user name</div>
        <!--//0 user entered it's own username 
            //1 successful
            //-1 exists before 
            //-2 username not valid 
            //-3 no special char 
            //-4 enter username -->
        <div class="nSettingsValidationErrorMessage nSettingsUNError0 invisible">You have entered the same user name.</div>
        <div class="nSettingsValidationErrorMessage nSettingsUNError1 nGreen invisible">The username sucessfully changed :)</div>
        <div class="nSettingsValidationErrorMessage nSettingsUNError-1 invisible">The username is not availble.</div>
        <div class="nSettingsValidationErrorMessage nSettingsUNError-2 invisible">The username is not valid.</div>
        <div class="nSettingsValidationErrorMessage nSettingsUNError-3 invisible">The username could not include any special character.</div>
        <div class="nSettingsValidationErrorMessage nSettingsUNError-4 invisible">The username could not be empty.</div>
        <hr class="nSettingsHr" />
        <div class="nSIRow">
            <div class="nSIview ">
                <div class="nSIRowTitle">Gender</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue nSIRowGender">Unknown</div>
            </div>
            <div class="nSImodify invisible nSImodifyGender">
                <br />
                <div class="nSIRowTitle">
                    <asp:DropDownList ID="DropDownListGender" runat="server" data-role="none" CssClass="nTextInput">
                        <asp:ListItem Value="0">Select</asp:ListItem>
                        <asp:ListItem Value="2">Female</asp:ListItem>
                        <asp:ListItem Value="1">Male</asp:ListItem>
                        <asp:ListItem Value="3">Other</asp:ListItem>
                    </asp:DropDownList>
                    <br />
                </div>
                <div class="nSIHelper nSIHelperGender">
                    <div class="nSIRowEnterArrow"></div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="nSettingsValidationErrorMessage nSettingsGenderError invisible">Please choose gender</div>
        <hr class="nSettingsHr" />
        <div class="nSIRow">
            <div class="nSIview ">
                <div class="nSIRowTitle">Birth Date</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue nSIRowDob">Unknown</div>
            </div>
            <div class="nSImodify invisible nSImodifyDOB">
                <div class="nSIRowTitle">
                    <br />
                    <input type="date" name="date" id="nSIDateInput" value="1961-08-04" data-role="none" class="nTextInput" />
                    <br />
                    <br />
                </div>
                <div class="nSIHelper nSIHelperDOB">
                    <div class="nSIRowEnterArrow"></div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="nSettingsValidationErrorMessage nSettingsDOBError invisible">Aren't you 18 yet?</div>
        <hr class="nSettingsHr" />
        <div class="nSIRow nSIRowAbout ">
            <div class="nSIview">
                <div class="nSIRowTitle">About</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue"></div>
                <div class="clear"></div>
                <div class="NSRowAboutValue NSRowAboutValueDiv">Unknown</div>
                <div class="clear"></div>
            </div>
            <div class="nSImodify invisible nSImodifyAbout">
                <br />
                <div class="nSIRowTitle">About</div>

                <div class="nSIHelper nSIHelperAbout">
                    <div class="nSIRowEnterArrow"></div>
                </div>
                <div class="clear"></div>
                <div class="NSRowAboutValue">
                    <br />
                    <asp:TextBox ID="TextBoxAbout" runat="server" CssClass="nTextInput" data-role="none"></asp:TextBox>
                    <br />
                    <br />
                </div>
                <div class="clear"></div>
                <br />
            </div>
        </div>
        <div class="invisible">
            <asp:HiddenField ID="HiddenFieldDOB" runat="server" />
        </div>
        <!--
            <asp:Label ID="LabelFirstName" runat="server" Text="First Name:" AssociatedControlID="TextBoxFirstName"></asp:Label>
            <asp:Label ID="LabelLastName" runat="server" AssociatedControlID="TextBoxLastName" Text="Last Name:"></asp:Label>
            <asp:Label ID="LabelUsername" runat="server" AssociatedControlID="TextBoxUsername" Text="Username:"></asp:Label>
            <asp:Label ID="LabelGender" runat="server" AssociatedControlID="DropDownListGender" Text="Gender:"></asp:Label>
            <asp:Label ID="LabelBirthdate" runat="server" Text="Birthdate:"></asp:Label>
            <asp:Label ID="LabelAbout" runat="server" AssociatedControlID="TextBoxAbout" Text="About:"></asp:Label>
            <asp:Label ID="LabelInformationMessage" runat="server" Visible="False"></asp:Label>
            
        -->
        <div class="nExploreFooter nThickFooter">
            <div class="nFooterButton nProfileMessageButton">&nbsp BACK TO SETTINGS</div>
        </div>
    </asp:Panel>

    <asp:Panel ID="PanelPhoto" runat="server" Visible="False">
        <script>
            $(document).ready(function () {
                $('.nPageTitle').html("Settings - Photo and Cover");
                settingsPhotos();
            });
        </script>
        <br />
        <div class="nRoundPicture nProfpagePicture nSPChooseFileButton">
        </div>
        <!-- <div class="nSPButton nSPChooseFileButton">CHOOSE FILE</div> -->
        <div class="nSPButton nSPUploadButton invisible">UPLOAD</div>
        <div class="nSPButton nSPRemoveButton">REMOVE</div>
        <br />
        <div class="nWrongLogin invisible">
            <div class="nWrongLoginIcon"></div>
            <b>
                <asp:Label ID="LabelPhotoMessage" runat="server" Visible="False"></asp:Label></b>
        </div>
        <hr class="nSettingsHr" />
        <br />
        <div class="nSPCoverHolder">
            <label>Choose the event's cover</label>
            <br />
            <div class="nSPCoverHolder">
                <div class="nSPCoverPhoto" activity-id="101">
                    <!-- <div class="nSPCoverPhotoTransparent"></div> -->
                </div>
            </div>
            <br />
            <div class="nEALogosContainer">
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="101"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="102"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="103"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="104"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="201"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="202"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="203"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="301"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="302"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="303"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="304"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="401"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="402"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="403"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="404"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="405"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="406"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="501"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="502"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="503"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="504"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="505"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="506"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="601"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="701"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="702"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="703"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="704"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="705"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="706"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="707"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="708"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="709"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="710"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="711"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="801"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="802"></div>
                </div>
                <div class="nSearchLogoContainer nSPLogoContainer ">
                    <div class="nSearchLogo nSPLogo" activity-id="803"></div>
                </div>
            </div>
            <br />
        </div>
        <div class="nExploreFooter nThickFooter">

            <div class="nFooterButton nProfileMessageButton">&nbsp BACK TO SETTINGS</div>
        </div>

        <div class="invisible">
            <asp:FileUpload ID="FileUploadPicture" runat="server" CssClass="nSPAspChooseButton" />
            <asp:Button ID="ButtonPhoto" runat="server" Text="Upload" OnClick="ButtonPhoto_Click" CssClass="nSPAspUploadButton" />
            <asp:Button ID="ButtonPhotoRemove" runat="server" Text="Upload" OnClick="ButtonPhotoRemove_Click" />
            <asp:HiddenField ID="HiddenFieldPhotoUrl" runat="server" />
        </div>
    </asp:Panel>

    <asp:Panel ID="PanelLocation" runat="server" Visible="False">

        <script>
            $(document).ready(function () {
                $('.nPageTitle').html("Settings - Location");
                settingsLocation();
            });
        </script>
        <div class="nSIRow">
            <div class="nSIview nSIviewLocation">
                <div class="nSIRowTitle">Current Location</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue nSIRowLocation">
                    <asp:Label ID="LabelLocation" runat="server"></asp:Label>
                </div>
            </div>
            <div class="nSImodify invisible nSImodifyFirstName">
                <div class="nSIRowTitle">
                    <br />
                    <asp:DropDownList ID="DropDownListCountry" runat="server" AutoPostBack="false" CssClass="nTextInput"
                        OnSelectedIndexChanged="DropDownListCountry_SelectedIndexChanged" data-role="none">
                    </asp:DropDownList>
                    <br />
                    <br />
                    <asp:DropDownList ID="DropDownListCity" runat="server" data-theme="b" data-role="none" CssClass="nTextInput">
                        <asp:ListItem Value="0">Select City</asp:ListItem>
                    </asp:DropDownList>
                    <br />
                    <br />
                </div>
                <div class="nSIHelper nSIHelperLocation">
                    <div class="nSIRowEnterArrow"></div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="nSettingsValidationErrorMessage nSettingsLocationError invisible">Please choose the location</div>
        <hr class="nSettingsHr" />
        <!--<div class="nSIRow">
            <div class="nSIview">
                <div class="nSIRowTitle">Detect Location Automatically</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue nSIRowLocation">Unknown</div>
            </div>
            <div class="nSImodify invisible ">
                <div class="nSIRowTitle">
                    <select name="flip-1" class="nSLLocationFlip" data-role="slider" data-mini="true">
                        <option value="off">Off</option>
                        <option value="on">On</option>
                    </select>
                </div>
                <div class="nSIRowEnterArrow"></div>

            </div>
            <div class="clear"></div>
        </div>
        <hr class="nSettingsHr" />
        <!-- needs update -->
        <div class="nSettingsValidationErrorMessage nSettingsFNError invisible">Please enter a valid first name</div>
        <!--
            
            <asp:Label ID="LabelDistance" runat="server" Text="Distance Covered:"></asp:Label>
            <input type="range" name="slider-fill-mini" id="distanceSlider" value="40" min="0" max="100" data-mini="true" data-highlight="true" data-theme="a" data-track-theme="a" />
            <select name="flip-2" id="locationDetectionFlip" data-role="slider" data-mini="true">
                <option value="off">Off</option>
                <option value="on">On</option>
            </select>
        <asp:Button ID="ButtonLocation" runat="server" OnClick="ButtonLocation_Click" Text="Save Changes" />
        <asp:Label ID="LabelLocationMessage" runat="server" Visible="False"></asp:Label>
        
        <asp:HiddenField ID="HiddenFieldCurrentCity" runat="server" />
        
            -->
        <div class="nExploreFooter nThickFooter">
            <div class="nFooterButton nProfileMessageButton">&nbsp BACK TO SETTINGS</div>
        </div>
    </asp:Panel>

    <asp:Panel ID="PanelPreferences" runat="server" Visible="False">
        <script>
            $(document).ready(function () {
                $('.nPageTitle').html("Settings - Preferences");
                settingsPreferences();
            });
        </script>
        <div class="nSIRow">
            <div class="nSIview ">
                <div class="nSIRowTitle">Notification emails</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue nSIRowEmails">Unknown</div>
            </div>
            <div class="nSImodify invisible">
                <div class="nSIRowTitle">
                    <select name="flip-2" id="emailNotificationFlip" data-role="slider" data-mini="true">
                        <option value="off">Off</option>
                        <option value="on">On</option>
                    </select>
                </div>
                <div class="nSIHelper nSIHelperEmailNotification">
                    <div class="nSIRowEnterArrow"></div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <hr class="nSettingsHr" />
        <!--<div class="nSIRow">
            <div class="nSIview">
                <div class="nSIRowTitle">Sound</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue nSIRowSounds">Unknown</div>
            </div>
            <div class="nSImodify invisible">
                <div class="nSIRowTitle">
                    <select name="flip-2" id="soundFlip" data-role="slider" data-mini="true">
                        <option value="off">Off</option>
                        <option value="on">On</option>
                    </select>
                </div>
                <div class="nSIRowEnterArrow"></div>
            </div>
            <div class="clear"></div>
        </div>-->
        <div class="nExploreFooter nThickFooter">
            <div class="nFooterButton nProfileMessageButton">&nbsp BACK TO SETTINGS</div>
        </div>
        <asp:HiddenField ID="HiddenFieldNotifications" runat="server" />
        <asp:HiddenField ID="HiddenFieldSound" runat="server" />
        <!--
            <asp:Button ID="ButtonPereferences" runat="server" Text="Save Changes" OnClick="ButtonPereferences_Click" />
            <asp:Label ID="LabelPereferencesMessage" runat="server" Visible="False"></asp:Label>    
        -->
    </asp:Panel>

    <asp:Panel ID="PanelAccount" runat="server" Visible="False">
        <script>
            $(document).ready(function () {
                $('.nPageTitle').html("Settings - Account");
                settingsAccount();
            });
        </script>
        <div class="nSIRow">
            <div class="nSIview nSAchangePassword">
                <div class="nSIRowTitle">Change Password</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue"></div>
            </div>
            <div class="nSImodify invisible nSImodifyPassword">
                <div class="nSIRowTitle">
                    <br />
                    <asp:TextBox ID="TextBoxPasswordOld" runat="server" TextMode="Password" placeholder="Old password" data-mini="true" data-role="none" CssClass="nSettingsOldPassword nTextInput"></asp:TextBox>
                    <br />
                    <br />
                    <asp:TextBox ID="TextBoxPasswordNew" runat="server" TextMode="Password" placeholder="New password" data-mini="true" data-role="none" CssClass="nTextInput"></asp:TextBox>
                    <br />
                    <br />
                    <asp:TextBox ID="TextBoxPasswordNew2" runat="server" TextMode="Password" placeholder="Re-enter new password" data-mini="true" data-role="none" CssClass="nTextInput"></asp:TextBox>
                    <br />
                    <br />
                </div>
                <div class="nSIHelper nSIHelperPassword">
                    <div class="nSIRowEnterArrow"></div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="nSettingsPasswordErrorContainer">
            <asp:Label ID="LabelPasswordMessage" runat="server" Visible="False"></asp:Label>
        </div>
        <hr class="nSettingsHr" />
        <div class="nSIRow">
            <div class="nSIview ">
                <div class="nSIRowTitle">Account Details</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue">
                </div>
            </div>
            <div class="nSImodify invisible">
                <div class="nSIRowTitle">
                    <div class="nLeft">
                        <div class="nSAEmailLabel">
                            <asp:Label ID="LabelEmail" runat="server" Text="E-mail Address:"></asp:Label>
                        </div>
                    </div>
                    <div class="nLeft nSACheck nSACheckEmail">
                        <asp:Image ID="ImageEmailStatus" runat="server" />
                    </div>
                    <div class="clear"></div>
                    <div class="nLeft">
                        <div class="nSVerifyEmailContainer invisible">
                            <div class="nSAVerifyEmail nProfileFollowButton nGreenBG ">Verify Email</div>
                            <br />
                        </div>
                        <div class="nSVerifyEmailMessage invisible">
                            The verification Email has been just sent to you.
                            <br />
                            <br />
                        </div>

                    </div>
                    <!-- <div class="nSLVerifyEmail">Verify Email</div>
                            <asp:TextBox ID="TextBoxMobile" runat="server" Type="number" data-role="none"></asp:TextBox> -->
                </div>
                <div class="nLeft nSACheck">
                </div>
                <div class="nSIHelper nSIHelperEmailPhone invisible">
                    <div class="nSIRowEnterArrow"></div>
                </div>
            </div>
        </div>
        <div class="clear"></div>
        <div class="nSettingsValidationErrorMessage nSettingsEmailError invisible">Please enter a valid Email address</div>
        <hr class="nSettingsHr" />
        <!-- <div class="nSIRow">
            <div class="nSIview ">
                <div class="nSIRowTitle">Deactivate Account</div>
                <div class="nSIRowViewArrow"></div>
                <div class="nSIRowValue"></div>
            </div>
            <div class="nSImodify invisible">
                <div class="nSIRowTitle">
                    <div class="nProfileFollowButton">De-active</div>
                </div>
                <div class="nSIRowEnterArrow"></div>
            </div>
            <div class="clear"></div>
            <asp:Label ID="LabelDeactivateMessage" runat="server" Visible="False"></asp:Label>
        </div>
            -->
        <asp:HiddenField ID="HiddenFieldMobile" runat="server" />
        <div class="invisible">
            <asp:LinkButton ID="LinkButtonActivate" runat="server" OnClick="LinkButtonActivate_Click">De-activate Account</asp:LinkButton>
        </div>
        <div class="nExploreFooter nThickFooter">
            <div class="nFooterButton nProfileMessageButton">&nbsp BACK TO SETTINGS</div>
        </div>
        <!--
            <asp:Label ID="LabelPassword" runat="server" Text="Password"></asp:Label></h3>
            <asp:Label ID="LabelPasswordOld" runat="server" AssociatedControlID="TextBoxPasswordOld" Text="Current Password:"></asp:Label>
            <asp:Label ID="Label2" runat="server" AssociatedControlID="TextBoxPasswordNew" Text="New Password:"></asp:Label>
            <asp:Label ID="Label3" runat="server" AssociatedControlID="TextBoxPasswordNew2" Text="Re-type New Password:"></asp:Label>
            
            
            
            
            
            <asp:Label ID="LabelMobile" runat="server" Text="Phone Number:"></asp:Label>
            
            <asp:Label ID="LabelAccountMessage" runat="server" Visible="False"></asp:Label>
   
            <asp:HiddenField ID="HiddenFieldEmail" runat="server" />
            
            -->
    </asp:Panel>
    <asp:Panel ID="PanelPrivacy" runat="server" Visible="False">
        <!--
      

        
                <!-- /content 
            </div>

        </div>

            -->
    </asp:Panel>
    <asp:HiddenField ID="HiddenFieldValue" runat="server" />
    <asp:HiddenField ID="HiddenFieldStatus" runat="server" />
    <asp:HiddenField ID="HiddenFieldFStatus" runat="server" Value="1" />
    <div class="invisible">
        <asp:Button ID="ButtonSubmit" runat="server" Text="Button" CommandArgument="blank" OnClick="ButtonSubmit_Click" />
        <asp:Button ID="ButtonPassword" runat="server" Text="Change Password" OnClick="ButtonPassword_Click" />
    </div>
    <asp:HiddenField ID="HiddenFieldMode" runat="server" />
    <asp:HiddenField ID="HiddenFieldPStatus" runat="server" />
    <asp:HiddenField ID="HiddenFieldStep" runat="server" />
    <asp:HiddenField ID="HiddenFieldCoverId" runat="server" />
    <asp:HiddenField ID="HiddenFieldLocationId" runat="server" />
    <asp:HiddenField ID="HiddenFieldEmailVerify" runat="server" Value="false" />
</asp:Content>
